# -*- coding: utf-8 -*-
"""Русские термины для IT-понятий без lang=ru."""
import os, sys, re
from collections import defaultdict
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from fill_props import finish
from jnana_engine import JnanaEngine

# точные соответствия nama → русский термин
GLOSS = {
    "information object": "информационный объект",
    "data": "данные",
    "database": "база данных",
    "file": "файл",
    "log file": "файл журнала",
    "relational database": "реляционная база данных",
    "NoSQL database": "нереляционная база данных",
    "database table": "таблица базы данных",
    "commit": "фиксация изменений",
    "version": "версия",
    "request": "запрос",
    "response": "ответ",
    "software": "программное обеспечение",
    "system software": "системное ПО",
    "operating system": "операционная система",
    "application software": "прикладное ПО",
    "hardware": "аппаратное обеспечение",
    "computer network": "компьютерная сеть",
    "server": "сервер",
    "web server": "веб-сервер",
    "database server": "сервер баз данных",
    "client": "клиент",
    "source code": "исходный код",
    "object code": "объектный код",
    "bytecode": "байт-код",
    "compiler": "компилятор",
    "interpreter": "интерпретатор",
    "debugger": "отладчик",
    "linker": "компоновщик",
    "assembler": "ассемблер",
    "algorithm": "алгоритм",
    "bug": "ошибка программы",
    "error": "ошибка",
    "exception": "исключение",
    "variable": "переменная",
    "function": "функция",
    "method": "метод",
    "class": "класс",
    "object": "объект",
    "module": "модуль",
    "package": "пакет",
    "library": "библиотека",
    "framework": "каркас",
    "interface specification": "спецификация интерфейса",
    "API": "программный интерфейс",
    "operator": "оператор",
    "operand": "операнд",
    "expression": "выражение",
    "statement": "инструкция",
    "loop": "цикл",
    "array": "массив",
    "stack": "стек",
    "queue": "очередь",
    "heap": "куча",
    "hash table": "хеш-таблица",
    "linked list": "связный список",
    "record": "запись",
    "pointer": "указатель",
    "string": "строка",
    "integer": "целое число",
    "boolean": "логический тип",
    "character": "символ",
    "floating-point": "число с плавающей точкой",
    "void": "пустой тип",
    "constant": "константа",
    "literal": "литерал",
    "keyword": "ключевое слово",
    "identifier": "идентификатор",
    "comment": "комментарий",
    "token": "лексема",
    "block": "блок",
    "parameter": "параметр",
    "argument": "аргумент",
    "procedure": "процедура",
    "subroutine": "подпрограмма",
    "constructor": "конструктор",
    "inheritance": "наследование",
    "polymorphism": "полиморфизм",
    "encapsulation": "инкапсуляция",
    "data type": "тип данных",
    "data structure": "структура данных",
    "data format": "формат данных",
    "file format": "формат файла",
    "programming language": "язык программирования",
    "markup language": "язык разметки",
    "query language": "язык запросов",
    "scripting language": "язык сценариев",
    "assembly language": "язык ассемблера",
    "machine language": "машинный язык",
    "high-level language": "язык высокого уровня",
    "low-level language": "язык низкого уровня",
    "object-oriented language": "объектно-ориентированный язык",
    "functional language": "функциональный язык",
    "procedural language": "процедурный язык",
    "logic programming language": "язык логического программирования",
    "programming paradigm": "парадигма программирования",
    "object-oriented programming": "объектно-ориентированное программирование",
    "functional programming": "функциональное программирование",
    "procedural programming": "процедурное программирование",
    "declarative programming": "декларативное программирование",
    "imperative programming": "императивное программирование",
    "logic programming": "логическое программирование",
    "event-driven programming": "событийно-ориентированное программирование",
    "operating system": "операционная система",
    "version control": "управление версиями",
    "version control system": "система управления версиями",
    "language construct": "языковая конструкция",
    "computing process": "вычислительный процесс",
    "development": "разработка",
    "development tool": "средство разработки",
    "coding": "кодирование",
    "compilation": "компиляция",
    "debugging": "отладка",
    "testing": "тестирование",
    "deployment": "развёртывание",
    "execution": "выполнение",
    "operation": "операция",
    "backup": "резервное копирование",
    "encryption": "шифрование",
    "parsing": "разбор",
    "linking": "компоновка",
    "recursion": "рекурсия",
    "garbage collection": "сборка мусора",
    "exception handling": "обработка исключений",
    "unit testing": "модульное тестирование",
    "code refactoring": "рефакторинг",
    "syntax error": "синтаксическая ошибка",
    "runtime error": "ошибка выполнения",
    "overflow error": "ошибка переполнения",
    "computer error": "ошибка компьютера",
    "conditional statement": "условная инструкция",
    "if statement": "условный оператор if",
    "return statement": "инструкция возврата",
    "assignment": "присваивание",
    "declaration": "объявление",
    "for loop": "цикл for",
    "while loop": "цикл while",
    "foreach": "цикл foreach",
    "endless loop": "бесконечный цикл",
    "command": "команда",
    "branch": "ветвление",
    "program": "программа",
    "executable": "исполняемый файл",
    "script": "скрипт",
    "source code": "исходный код",
    "pseudocode": "псевдокод",
    "SDK": "комплект средств разработки",
    "IDE": "среда разработки",
    "API": "программный интерфейс",
    "CPU": "процессор",
    "network device": "сетевое устройство",
    "firewall": "межсетевой экран",
    "router": "маршрутизатор",
    "switch": "коммутатор",
    "workstation": "рабочая станция",
    "device driver": "драйвер устройства",
    "firmware": "встроенное ПО",
    "desktop application": "настольное приложение",
    "web application": "веб-приложение",
    "mobile application": "мобильное приложение",
    "frontend": "клиентская часть",
    "backend": "серверная часть",
    "developer": "разработчик",
    "programmer": "программист",
    "tester": "тестировщик",
    "end user": "конечный пользователь",
    "system administrator": "системный администратор",
    "system analyst": "системный аналитик",
    "IT role": "роль в IT",
    "quality attribute": "атрибут качества",
    "availability": "доступность",
    "reliability": "надёжность",
    "scalability": "масштабируемость",
    "maintainability": "сопровождаемость",
    "usability": "удобство использования",
    "performance": "производительность",
    "security": "безопасность",
    "confidentiality": "конфиденциальность",
    "integrity": "целостность",
    "container": "контейнер",
    "containerization": "контейнеризация",
    "orchestration": "оркестрация",
    "querying": "запрос данных",
    "monitoring": "мониторинг",
    "maintenance": "сопровождение",
    "patching": "внесение исправлений",
    "patch": "заплатка",
    "release": "выпуск",
    "failure": "сбой",
    "data loss": "потеря данных",
    "segfault": "ошибка сегментации",
    "repository": "репозиторий",
    "protocol": "протокол",
    "thread": "поток выполнения",
    "memory": "память",
    "table": "таблица",
    "matrix": "матрица",
    "model": "модель",
    "value": "значение",
    "feature": "возможность",
    "property": "свойство",
    "standard": "стандарт",
    "specification": "спецификация",
    "encoding": "кодировка",
    "classification": "классификация",
    "collection": "коллекция",
    "combination": "комбинация",
    "dialect": "диалект",
    "paradigm": "парадигма",
    "approach": "подход",
    "technique": "приём",
    "style": "стиль",
    "method": "метод",
    "subset": "подмножество",
    "problem": "задача",
    "tool": "инструмент",
    "build": "сборка",
    "coding": "кодирование",
    "compile": "компиляция",
    "debug": "отладка",
    "database system": "система баз данных",
    "database server": "сервер БД",
    "web server": "веб-сервер",
    "software component": "компонент ПО",
    "software architecture": "архитектура ПО",
    "software interface": "программный интерфейс",
    "software library": "библиотека ПО",
    "software compiler": "компилятор",
    "computer program": "компьютерная программа",
    "computer language": "компьютерный язык",
    "computer science": "информатика",
    "formal language": "формальный язык",
    "natural language": "естественный язык",
    "query language": "язык запросов",
    "style sheet language": "язык таблиц стилей",
    "intermediate language": "промежуточный язык",
    "command language": "командный язык",
    "general-purpose language": "язык общего назначения",
    "high-level programming language": "язык программирования высокого уровня",
    "low-level programming language": "язык программирования низкого уровня",
    "object-oriented programming language": "объектно-ориентированный язык программирования",
    "functional programming language": "функциональный язык программирования",
    "multi-paradigm programming language": "мультипарадигмальный язык",
    "abstract programming language": "абстрактный язык программирования",
    "open source scripting language": "открытый язык сценариев",
    "first generation language": "язык первого поколения",
    "second generation language": "язык второго поколения",
    "third-generation programming language": "язык третьего поколения",
    "fourth generation language": "язык четвёртого поколения",
    "fifth generation language": "язык пятого поколения",
    "global variable": "глобальная переменная",
    "private variable": "закрытая переменная",
    "bitwise operator": "побитовый оператор",
    "logical operator": "логический оператор",
    "arithmetic operator": "арифметический оператор",
    "unary operator": "унарный оператор",
    "ternary operator": "тернарный оператор",
    "dereference operator": "оператор разыменования",
    "XOR operator": "оператор исключающего ИЛИ",
    "OR operator": "оператор ИЛИ",
    "bitwise operation": "побитовая операция",
    "control flow": "управление потоком",
    "exception handling": "обработка исключений",
    "lexical analysis": "лексический анализ",
    "unit testing": "модульное тестирование",
    "fuzz testing": "фаззинг",
    "monkey testing": "обезьянье тестирование",
    "automated unit testing": "автоматизированное модульное тестирование",
    "full stack developer": "fullstack-разработчик",
    "system analyst": "системный аналитик",
    "network device": "сетевое устройство",
    "web application": "веб-приложение",
    "mobile application": "мобильное приложение",
    "desktop application": "настольное приложение",
    "device driver": "драйвер",
    "runtime environment": "среда выполнения",
    "runtime error": "ошибка времени выполнения",
    "syntax error": "синтаксическая ошибка",
    "overflow error": "переполнение",
    "human error": "человеческая ошибка",
    "false positive": "ложная тревога",
    "race condition": "состояние гонки",
    "access violation": "нарушение доступа",
    "dead code": "мёртвый код",
    "spaghetti code": "спагетти-код",
    "glue code": "связующий код",
    "hard code": "жёстко заданный код",
    "obfuscated code": "обфусцированный код",
    "source code": "исходный код",
    "object file": "объектный файл",
    "batch file": "пакетный файл",
    "flat file": "плоский файл",
    "data file": "файл данных",
    "code block": "блок кода",
    "code page": "кодовая страница",
    "character code": "код символа",
    "escape sequence": "escape-последовательность",
    "null character": "нулевой символ",
    "wide character": "широкий символ",
    "reserved character": "зарезервированный символ",
    "curly bracket": "фигурная скобка",
    "punctuation mark": "знак препинания",
    "parenthesis": "круглая скобка",
    "bracket": "скобка",
    "delimiter": "разделитель",
    "foreign key": "внешний ключ",
    "hash table": "хеш-таблица",
    "lookup table": "таблица поиска",
    "array of pointers": "массив указателей",
    "event listener": "обработчик события",
    "background thread": "фоновый поток",
    "callback": "обратный вызов",
    "closure": "замыкание",
    "instance": "экземпляр",
    "instantiation": "создание экземпляра",
    "iteration": "итерация",
    "increment": "инкремент",
    "decrement": "декремент",
    "overload": "перегрузка",
    "method overloading": "перегрузка методов",
    "constructor chaining": "цепочка конструкторов",
    "dynamic binding": "динамическое связывание",
    "tail recursion": "хвостовая рекурсия",
    "memoization": "мемоизация",
    "sandbox": "песочница",
    "snippet": "фрагмент кода",
    "syntax": "синтаксис",
    "semantics": "семантика",
    "syntactic sugar": "синтаксический сахар",
    "operator precedence": "приоритет операторов",
    "order of operations": "порядок операций",
    "switch statement": "оператор switch",
    "conditional expression": "условное выражение",
    "conditional block": "условный блок",
    "if else": "если-иначе",
    "else if": "иначе если",
    "else": "иначе",
    "while": "пока",
    "true": "истина",
    "false": "ложь",
    "null": "пустое значение",
    "NaN": "не число",
    "flag": "флаг",
    "event": "событие",
    "transaction": "транзакция",
    "pipeline": "конвейер",
    "socket": "сокет",
    "shell": "оболочка",
    "workspace": "рабочее пространство",
    "tech stack": "стек технологий",
    "software engineering": "программная инженерия",
    "software development phases": "этапы разработки ПО",
    "web development": "веб-разработка",
    "reverse engineering": "обратная разработка",
    "unit test": "модульный тест",
    "hello world": "программа «hello world»",
    "halting problem": "проблема остановки",
    "binary search": "двоичный поиск",
    "bubble sort": "сортировка пузырьком",
    "hash": "хеш",
    "mutex": "мьютекс",
    "semaphore": "семафор",
    "deadlock": "взаимная блокировка",
    "race condition": "состояние гонки",
    "base address": "базовый адрес",
    "absolute address": "абсолютный адрес",
    "stack pointer": "указатель стека",
    "return address": "адрес возврата",
    "persistent memory": "постоянная память",
    "virtual machine": "виртуальная машина",
    "bytecode": "байт-код",
    "compiler infrastructure": "инфраструктура компилятора",
    "transcompiler": "транскомпилятор",
    "decompiler": "декомпилятор",
    "disassembler": "дизассемблер",
    "native compiler": "нативный компилятор",
    "multi-pass compiler": "многопроходный компилятор",
    "one-pass compiler": "однопроходный компилятор",
    "hex editor": "шестнадцатеричный редактор",
    "css editor": "редактор CSS",
    "css compressor": "сжиматель CSS",
    "relational algebra": "реляционная алгебра",
    "deductive database": "дедуктивная база данных",
    "data source": "источник данных",
    "data flow diagram": "диаграмма потоков данных",
    "data-flow analysis": "анализ потока данных",
    "control flow": "поток управления",
    "input stream": "входной поток",
    "stdin": "стандартный ввод",
    "eof": "конец файла",
    "bom": "маркер порядка байтов",
    "csv": "значения, разделённые запятыми",
    "xml": "расширяемый язык разметки",
    "html": "язык гипертекстовой разметки",
    "json": "нотация объектов JavaScript",
    "yaml": "YAML",
    "sql": "язык структурированных запросов",
    "css": "каскадные таблицы стилей",
    "ajax": "асинхронный JavaScript и XML",
    "dom": "объектная модель документа",
    "regex": "регулярное выражение",
    "repl": "цикл чтение-вычисление-печать",
    "sdk": "комплект разработки ПО",
    "jdk": "комплект разработки Java",
    "jre": "среда выполнения Java",
    "jvm": "виртуальная машина Java",
    "jdbc": "соединение Java с БД",
    "jsp": "страницы Java-сервера",
    "git": "гит",
    "github": "GitHub",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "linux": "Linux",
    "macos": "macOS",
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "absolute coding": "абсолютное кодирование",
    "action statement": "инструкция действия",
    "adaptive technology": "адаптивная технология",
    "agile development methods": "гибкие методы разработки",
    "alert": "оповещение",
    "allocate": "выделение памяти",
    "applet": "апплет",
    "application software": "прикладное ПО",
    "arithmetic": "арифметика",
    "associative operation": "ассоциативная операция",
    "automation": "автоматизация",
    "automata-based programming": "программирование на автоматах",
    "availability": "доступность",
    "backend": "серверная часть",
    "bind": "привязка",
    "bit shift": "сдвиг битов",
    "block-based programming": "блочное программирование",
    "block-level element": "блочный элемент",
    "browse": "просмотр",
    "bug tracking": "учёт ошибок",
    "build computer": "сборочный компьютер",
    "call": "вызов",
    "camelcase": "верблюжья нотация",
    "capture": "захват",
    "cgi": "общий шлюзовой интерфейс",
    "chaos model": "модель хаоса",
    "classpath": "путь классов",
    "closure": "замыкание",
    "code": "код",
    "code refactoring": "рефакторинг кода",
    "collaborative programming": "совместное программирование",
    "commutative operation": "коммутативная операция",
    "compile": "компиляция",
    "complementarity": "дополнительность",
    "component": "компонент",
    "compute": "вычисление",
    "computer designated": "выделенный компьютер",
    "computer instructions": "машинные инструкции",
    "computer programming algorithm": "алгоритм программирования",
    "computer programming language": "язык программирования",
    "computer programming paradigm": "парадигма программирования",
    "concat": "конкатенация",
    "concurrency": "параллелизм",
    "condition": "условие",
    "constructor chaining": "цепочка конструкторов",
    "content migration": "миграция содержимого",
    "control parameter": "управляющий параметр",
    "crapplet": "плохой апплет",
    "curly bracket": "фигурная скобка",
    "data flow diagram": "диаграмма потоков данных",
    "data source": "источник данных",
    "database terms": "термины баз данных",
    "dataflow programming": "потоковое программирование",
    "dead code": "мёртвый код",
    "debug": "отладка",
    "decompiler": "декомпилятор",
    "delimiter": "разделитель",
    "demote": "понижение",
    "dense matrix": "плотная матрица",
    "dependent variable": "зависимая переменная",
    "deprecated": "устаревшее",
    "devops": "DevOps",
    "dhtml": "динамический HTML",
    "die": "завершение с ошибкой",
    "diff": "сравнение различий",
    "discrete optimization": "дискретная оптимизация",
    "dump": "дамп",
    "dynamic dump": "динамический дамп",
    "dynamic binding": "динамическое связывание",
    "element": "элемент",
    "ellipsis": "многоточие",
    "embedded java": "встроенная Java",
    "encode": "кодирование",
    "endian": "порядок байтов",
    "epoch": "эпоха (время UNIX)",
    "equal": "равно",
    "errorlevel": "код ошибки",
    "eval": "вычисление выражения",
    "event listener": "слушатель события",
    "exec": "выполнение",
    "exists": "существует",
    "exit status": "код завершения",
    "exponent": "показатель степени",
    "exponential backoff": "экспоненциальная задержка",
    "factorial": "факториал",
    "false positive": "ложноположительный",
    "feature complete": "функционально полный",
    "first-class object": "объект первого класса",
    "flag": "флаг",
    "foo": "фиктивное имя",
    "for": "цикл for",
    "function call": "вызов функции",
    "garbage collection": "сборка мусора",
    "glitch": "сбой",
    "glob": "маска имён",
    "global variable": "глобальная переменная",
    "goto": "оператор безусловного перехода",
    "graphical representation": "графическое представление",
    "greedy": "жадный алгоритм",
    "hackathon": "хакатон",
    "halting problem": "проблема остановки",
    "hard code": "жёсткое кодирование",
    "hash": "хеширование",
    "hello world": "пример «hello world»",
    "heuristic evaluation": "эвристическая оценка",
    "hex editor": "hex-редактор",
    "hungarian notation": "венгерская нотация",
    "human error": "ошибка человека",
    "idempotence": "идемпотентность",
    "if": "если",
    "immutable object": "неизменяемый объект",
    "implicit parallelism": "неявный параллелизм",
    "indirect address": "косвенный адрес",
    "inherent error": "неустранимая ошибка",
    "inline": "подстановка",
    "input/output statement": "инструкция ввода-вывода",
    "instruction storage interrupt": "прерывание хранения инструкции",
    "integrity": "целостность",
    "interpreted": "интерпретируемый",
    "invalid": "недопустимое",
    "iteration": "итерация",
    "label": "метка",
    "lambda calculus": "лямбда-исчисление",
    "language": "язык",
    "language processor": "процессор языка",
    "large language model": "большая языковая модель",
    "large quantity": "большое количество",
    "lexicon": "лексикон",
    "lifecycle": "жизненный цикл",
    "link time": "время компоновки",
    "local optimum": "локальный оптимум",
    "logical operation": "логическая операция",
    "loophole": "лазейка",
    "loosely typed language": "язык со слабой типизацией",
    "low-code": "низкокодовая разработка",
    "magic quotes": "магические кавычки",
    "map": "отображение",
    "math": "математика",
    "math operation": "математическая операция",
    "mathematical operation": "математическая операция",
    "metacharacter": "метасимвол",
    "metaclass": "метакласс",
    "metalanguage": "метаязык",
    "meta tag": "метатег",
    "middleware": "промежуточное ПО",
    "modular programming": "модульное программирование",
    "multiply": "умножение",
    "native language": "родных язык платформы",
    "nested loops join": "соединение вложенными циклами",
    "nil pointer": "нулевой указатель",
    "no-code": "бескодовая разработка",
    "no operation instructions": "пустая инструкция",
    "non-contiguous data structure": "несмежная структура данных",
    "nonexecutable statement": "неисполняемая инструкция",
    "object module": "объектный модуль",
    "object-oriented": "объектно-ориентированный",
    "opcode": "код операции",
    "open-source version control system": "открытая система версий",
    "operator associatively": "ассоциативность операторов",
    "overflow error": "ошибка переполнения",
    "parse": "разбор",
    "portable language": "переносимый язык",
    "positional parameter": "позиционный параметр",
    "print": "печать",
    "private": "закрытый",
    "program generator": "генератор программ",
    "program language": "язык программ",
    "program listing": "распечатка программы",
    "programmable": "программируемый",
    "programming": "программирование",
    "programming conditional statement": "условная инструкция программирования",
    "programming in logic": "программирование в логике",
    "programming interface": "программный интерфейс",
    "programming language and variation": "язык программирования и вариант",
    "programming language paradigm": "парадигма языка",
    "programming technique": "техника программирования",
    "programming tool": "инструмент программирования",
    "properties": "свойства",
    "pseudo-class": "псевдокласс",
    "pseudo-operation": "псевдооперация",
    "pseudorandom": "псевдослучайное",
    "public": "открытый",
    "pull": "вытягивание",
    "push": "помещение в стек",
    "pop": "извлечение из стека",
    "quick-and-dirty": "на скорую руку",
    "race condition": "состояние гонки",
    "random": "случайное",
    "random seed": "зерно генератора",
    "range": "диапазон",
    "rank": "ранг",
    "real number": "вещественное число",
    "recompile": "перекомпиляция",
    "recursive": "рекурсивный",
    "recursive mathematical function": "рекурсивная математическая функция",
    "relational algebra": "реляционная алгебра",
    "repeat counter": "счётчик повторений",
    "repetition": "повторение",
    "reserved character": "зарезервированный символ",
    "return address": "адрес возврата",
    "routing algorithm": "алгоритм маршрутизации",
    "run time": "время выполнения",
    "safe font": "безопасный шрифт",
    "scalar": "скаляр",
    "schema matching": "сопоставление схем",
    "security descriptor definition language": "язык дескрипторов безопасности",
    "server-side": "на стороне сервера",
    "server-side scripting": "серверные сценарии",
    "shebang": "шебанг",
    "shift": "сдвиг",
    "short-circuit operator": "сокращённый оператор",
    "signedness": "знаковость",
    "simple sorting technique": "простая сортировка",
    "single step": "пошаговое выполнение",
    "snippet": "фрагмент",
    "soft": "программный",
    "software development method": "метод разработки ПО",
    "software development phases": "фазы разработки ПО",
    "source": "источник",
    "special purpose language": "язык специального назначения",
    "spooling": "спулинг",
    "stack pointer": "указатель стека",
    "standard attribute": "стандартный атрибут",
    "stream processing": "потоковая обработка",
    "strongly typed language": "язык с сильной типизацией",
    "stylesheet": "таблица стилей",
    "submit": "отправка",
    "subscript": "индекс",
    "substring": "подстрока",
    "subtract": "вычитание",
    "superclass": "суперкласс",
    "switch statement": "оператор выбора",
    "syntactic sugar": "синтаксический сахар",
    "system analysis": "системный анализ",
    "system development": "системная разработка",
    "systems engineer": "системный инженер",
    "tail recursion": "хвостовая рекурсия",
    "tech stack": "технологический стек",
    "technique in software development": "приём разработки ПО",
    "technology or approach": "технология или подход",
    "ternary": "тернарный",
    "theoretical computer science": "теоретическая информатика",
    "transaction": "транзакция",
    "true": "истина",
    "trunk": "основная ветка",
    "tuple": "кортеж",
    "turing completeness": "полнота по Тьюрингу",
    "undefined": "неопределённое",
    "undefined variable": "неопределённая переменная",
    "underflow": "потеря значимости",
    "unescape": "снятие экранирования",
    "unit test": "модульный тест",
    "unshift": "вставка в начало",
    "usage": "использование",
    "variable expression": "выражение с переменной",
    "variable-length field": "поле переменной длины",
    "version control": "контроль версий",
    "vibe coding": "вайб-кодинг",
    "waterfall model": "каскадная модель",
    "web development": "веб-разработка",
    "what is bit flip?": "инверсия бита",
    "what is line height?": "высота строки",
    "what is pdf converter?": "преобразователь PDF",
    "what is the information age?": "информационная эпоха",
    "whole number": "целое число",
    "wide character": "широкий символ",
    "windows driver kit": "набор драйверов Windows",
    "workspace": "рабочая область",
    "z-buffering": "z-буферизация",
    "zombie": "зомби-процесс",
    "ambient occlusion": "затенение окружением",
    "back-face culling": "отсечение невидимых граней",
    "backpropagation neural network": "сеть с обратным распространением",
    "block-level element": "блочный элемент",
    "circuit satisfiability problem": "задача выполнимости схемы",
    "commutative operation": "коммутативная операция",
    "content migration": "перенос содержимого",
    "eight queens problem": "задача восьми ферзей",
    "first-class object": "объект первого класса",
    "gaussian pyramid": "пирамида Гаусса",
    "genetic programming": "генетическое программирование",
    "heuristic evaluation": "эвристическая оценка",
    "immutable object": "неизменяемый объект",
    "input stream": "входной поток",
    "interface specification": "спецификация интерфейса",
    "java reserved words": "зарезервированные слова Java",
    "java native interface": "собственный интерфейс Java",
    "knights of lambda calculus": "рыцари лямбда-исчисления",
    "large language model": "большая языковая модель",
    "local optimum": "локальный оптимум",
    "loosely typed language": "слабо типизированный язык",
    "low-code": "low-code",
    "monte carlo method": "метод Монте-Карло",
    "nested loops join": "соединение вложенными циклами",
    "no operation instructions": "холостая инструкция",
    "object-oriented version": "объектно-ориентированная версия",
    "onmouseover": "событие наведения",
    "open-source version control system": "открытая система контроля версий",
    "operator associatively": "ассоциативность операторов",
    "pixel shader": "пиксельный шейдер",
    "portable language": "переносимый язык",
    "program generator": "генератор программ",
    "pseudo-class": "псевдокласс",
    "quick-and-dirty": "сделано наспех",
    "react native": "React Native",
    "real number": "вещественное число",
    "religion of chi": "«религия хи»",
    "repeat counter": "счётчик повторов",
    "reserved character": "зарезервированный символ",
    "routing algorithm": "алгоритм маршрутизации",
    "s-expression": "s-выражение",
    "safe font": "безопасный шрифт",
    "schema matching": "сопоставление схем",
    "server-side scripting": "серверные скрипты",
    "short-circuit operator": "короткозамкнутый оператор",
    "simulated annealing": "имитация отжига",
    "software development method": "метод разработки программ",
    "software library": "программная библиотека",
    "source-to-source compiler": "транслятор в исходный код",
    "special purpose language": "язык специального назначения",
    "standard attribute": "стандартный атрибут",
    "stream processing": "обработка потоков",
    "strongly typed language": "сильно типизированный язык",
    "stubroutine": "заглушка",
    "switch statement": "оператор switch",
    "system analysis": "системный анализ",
    "systems engineer": "системный инженер",
    "technique in software development": "приём разработки",
    "theoretical computer science": "теоретическая информатика",
    "true basic": "True BASIC",
    "turing completeness": "тьюринг-полнота",
    "undefined variable": "неопределённая переменная",
    "variable expression": "выражение-переменная",
    "variable-length field": "поле переменной длины",
    "version control system": "система контроля версий",
    "web development": "веб-разработка",
    "windows driver kit": "набор драйверов Windows",
    "windows server": "Windows Server",
    "xor operator": "исключающее ИЛИ",
    "y combinator": "комбинатор Y",
    "adaptive technology": "адаптивная технология",
    "aggregate": "агрегат",
    "alert": "предупреждение",
    "allocate": "выделение",
    "applet": "апплет",
    "array of pointers": "массив указателей",
    "associative operation": "ассоциативная операция",
    "automation": "автоматизация",
    "availability": "доступность",
    "back-face culling": "отсечение обратных граней",
    "background thread": "фоновый поток",
    "base address": "базовый адрес",
    "batch file": "командный файл",
    "bean": "бин",
    "bind": "привязка",
    "bit shift": "битовый сдвиг",
    "bitwise operation": "побитовая операция",
    "bitwise operator": "побитовый оператор",
    "block-based programming": "блочное программирование",
    "browse": "просмотр",
    "bug tracking": "отслеживание ошибок",
    "bytecode": "байт-код",
    "call": "вызов",
    "callback": "коллбэк",
    "capture": "захват",
    "cell style": "стиль ячейки",
    "character code": "код символа",
    "classpath": "путь к классам",
    "code page": "кодовая страница",
    "code refactoring": "рефакторинг",
    "collaborative programming": "совместное программирование",
    "command language": "командный язык",
    "comment": "комментарий",
    "commit": "коммит",
    "compile": "компиляция",
    "compiler infrastructure": "инфраструктура компилятора",
    "complementarity": "дополнительность",
    "component": "компонент",
    "compute": "вычисление",
    "computer error": "компьютерная ошибка",
    "computer instructions": "команды компьютера",
    "computer language": "компьютерный язык",
    "computer network": "компьютерная сеть",
    "computer program": "компьютерная программа",
    "concat": "сцепление",
    "concurrency": "конкурентность",
    "condition": "условие",
    "conditional expression": "условное выражение",
    "conditional statement": "условный оператор",
    "confidentiality": "конфиденциальность",
    "constant": "константа",
    "constructor": "конструктор",
    "container": "контейнер",
    "containerization": "контейнеризация",
    "control flow": "поток управления",
    "control parameter": "управляющий параметр",
    "css compressor": "сжиматель CSS",
    "css editor": "редактор CSS",
    "data file": "файл данных",
    "data format": "формат данных",
    "data loss": "потеря данных",
    "data structure": "структура данных",
    "data type": "тип данных",
    "data-flow analysis": "анализ потока данных",
    "database server": "сервер базы данных",
    "database system": "система базы данных",
    "database table": "таблица БД",
    "dead code": "мёртвый код",
    "debugger": "отладчик",
    "debugging": "отладка",
    "declaration": "объявление",
    "declarative programming": "декларативное программирование",
    "decrement": "декремент",
    "deductive database": "дедуктивная БД",
    "deployment": "развёртывание",
    "deprecated": "нерекомендуемое",
    "dereference operator": "оператор разыменования",
    "desktop application": "настольное приложение",
    "development": "разработка",
    "development tool": "инструмент разработки",
    "device driver": "драйвер устройства",
    "disassembler": "дизассемблер",
    "discrete optimization": "дискретная оптимизация",
    "dump": "дамп памяти",
    "dynamic binding": "динамическое связывание",
    "dynamic dump": "динамический дамп",
    "element": "элемент",
    "ellipsis": "многоточие",
    "else": "иначе",
    "else if": "иначе если",
    "embedded java": "встраиваемая Java",
    "encode": "кодировать",
    "encoding": "кодировка",
    "encryption": "шифрование",
    "end user": "конечный пользователь",
    "endian": "порядок байтов",
    "endless loop": "бесконечный цикл",
    "epoch": "эпоха",
    "equal": "равенство",
    "errorlevel": "уровень ошибки",
    "escape sequence": "экранирующая последовательность",
    "eval": "вычисление",
    "event": "событие",
    "event-driven programming": "событийное программирование",
    "event listener": "слушатель событий",
    "exception": "исключение",
    "exception handling": "обработка исключений",
    "exec": "исполнение",
    "executable": "исполняемый файл",
    "execution": "исполнение",
    "exists": "проверка существования",
    "exit status": "статус выхода",
    "exponent": "экспонента",
    "exponential backoff": "экспоненциальный откат",
    "expression": "выражение",
    "factorial": "факториал",
    "failure": "отказ",
    "false": "ложь",
    "false positive": "ложное срабатывание",
    "feature": "свойство-возможность",
    "feature complete": "полный по функциям",
    "file": "файл",
    "file format": "формат файла",
    "firewall": "брандмауэр",
    "firmware": "прошивка",
    "first-class object": "объект первого класса",
    "flag": "флаг",
    "flat file": "плоский файл",
    "floating-point": "плавающая точка",
    "for loop": "цикл for",
    "foreach": "цикл по элементам",
    "foreign key": "внешний ключ",
    "formal language": "формальный язык",
    "framework": "фреймворк",
    "frontend": "фронтенд",
    "full stack developer": "фулстек-разработчик",
    "function": "функция",
    "function call": "вызов функции",
    "functional language": "функциональный язык",
    "functional programming": "функциональное программирование",
    "functional programming language": "функциональный язык программирования",
    "fuzz testing": "фазз-тестирование",
    "garbage collection": "сборка мусора",
    "general-purpose language": "язык общего назначения",
    "genetic programming": "генетическое программирование",
    "git": "Git",
    "github": "GitHub",
    "global variable": "глобальная переменная",
    "glue code": "связующий код",
    "graphical representation": "графическое представление",
    "greedy": "жадный",
    "hackathon": "хакатон",
    "halting problem": "задача останова",
    "hard code": "хардкод",
    "hardware": "аппаратура",
    "hash table": "хеш-таблица",
    "hello world": "hello world",
    "heuristic evaluation": "эвристическая оценка",
    "hex editor": "шестнадцатеричный редактор",
    "high-level language": "язык высокого уровня",
    "high-level programming language": "высокоуровневый язык программирования",
    "html": "HTML",
    "human error": "ошибка человека",
    "hungarian notation": "венгерская нотация",
    "ide": "интегрированная среда разработки",
    "idempotence": "идемпотентность",
    "identifier": "идентификатор",
    "if statement": "оператор if",
    "immutable object": "неизменяемый объект",
    "imperative programming": "императивное программирование",
    "implicit parallelism": "неявный параллелизм",
    "increment": "инкремент",
    "indirect address": "косвенный адрес",
    "information object": "информационный объект",
    "inherent error": "присущая ошибка",
    "inheritance": "наследование",
    "inline": "встроенный",
    "input stream": "входной поток",
    "input/output statement": "оператор ввода-вывода",
    "instance": "экземпляр",
    "instantiation": "инстанцирование",
    "integer": "целое",
    "integrity": "целостность",
    "interface specification": "спецификация интерфейса",
    "intermediate language": "промежуточный язык",
    "interpretation": "интерпретация",
    "interpreted": "интерпретируемый",
    "interpreter": "интерпретатор",
    "invalid": "недопустимый",
    "it role": "роль в IT",
    "iteration": "итерация",
    "java": "Java",
    "javascript": "JavaScript",
    "json": "JSON",
    "keyword": "ключевое слово",
    "label": "метка",
    "lambda calculus": "лямбда-исчисление",
    "language construct": "конструкция языка",
    "language processor": "обработчик языка",
    "large language model": "большая языковая модель",
    "lexical analysis": "лексический анализ",
    "lexicon": "лексикон",
    "library": "библиотека",
    "lifecycle": "жизненный цикл",
    "link time": "время компоновки",
    "linked list": "связный список",
    "linker": "компоновщик",
    "linking": "компоновка",
    "linux": "Linux",
    "lisp": "Лисп",
    "literal": "литерал",
    "local optimum": "локальный оптимум",
    "log file": "журнал",
    "logic programming": "логическое программирование",
    "logic programming language": "язык логического программирования",
    "logical operation": "логическая операция",
    "logical operator": "логический оператор",
    "lookup table": "таблица перекодировки",
    "loop": "цикл",
    "loophole": "лазейка",
    "low-code": "low-code",
    "low-level language": "язык низкого уровня",
    "low-level programming language": "низкоуровневый язык программирования",
    "machine language": "машинный язык",
    "macos": "macOS",
    "magic quotes": "магические кавычки",
    "maintainability": "сопровождаемость",
    "maintenance": "сопровождение",
    "map": "карта",
    "markup language": "язык разметки",
    "math": "математика",
    "math operation": "математическая операция",
    "mathematical operation": "математическая операция",
    "matrix": "матрица",
    "memoization": "мемоизация",
    "memory": "память",
    "meta": "мета",
    "meta tag": "метатег",
    "metacharacter": "метасимвол",
    "metaclass": "метакласс",
    "metalanguage": "метаязык",
    "method": "метод",
    "method overloading": "перегрузка метода",
    "middleware": "промежуточное ПО",
    "mobile application": "мобильное приложение",
    "model": "модель",
    "modular programming": "модульное программирование",
    "module": "модуль",
    "monitoring": "мониторинг",
    "monkey testing": "хаотическое тестирование",
    "monte carlo method": "метод Монте-Карло",
    "multi-paradigm programming language": "мультипарадигменный язык",
    "multi-pass compiler": "многопроходный компилятор",
    "multiply": "умножение",
    "mutex": "мьютекс",
    "native compiler": "собственный компилятор",
    "native language": "родной язык",
    "natural language": "естественный язык",
    "nested loops join": "соединение вложенными циклами",
    "network device": "сетевое устройство",
    "nil pointer": "нулевой указатель",
    "no-code": "no-code",
    "no operation instructions": "пустые инструкции",
    "node.js": "Node.js",
    "nodelist": "список узлов",
    "non-contiguous data structure": "несмежная структура данных",
    "nonexecutable statement": "неисполняемый оператор",
    "nosql database": "база NoSQL",
    "null": "нуль",
    "null character": "нулевой символ",
    "object": "объект",
    "object code": "объектный код",
    "object file": "объектный файл",
    "object module": "объектный модуль",
    "object-oriented": "объектно-ориентированный",
    "object-oriented language": "объектно-ориентированный язык",
    "object-oriented programming": "ООП",
    "object-oriented programming language": "ОО-язык программирования",
    "object-oriented version": "ОО-версия",
    "obfuscated code": "запутанный код",
    "obtuse": "тупой",
    "one-pass compiler": "однопроходный компилятор",
    "opcode": "код операции",
    "open source scripting language": "открытый скриптовый язык",
    "open-source version control system": "открытая система версий",
    "openGL polygon": "полигон OpenGL",
    "operand": "операнд",
    "operating system": "операционная система",
    "operation": "операция",
    "operator": "оператор",
    "operator associatively": "ассоциативность операторов",
    "operator precedence": "приоритет операторов",
    "or operator": "оператор ИЛИ",
    "orchestration": "оркестрация",
    "order of operations": "порядок операций",
    "overflow error": "ошибка переполнения",
    "overload": "перегрузка",
    "package": "пакет",
    "paradigm": "парадигма",
    "parameter": "параметр",
    "parenthesis": "скобки",
    "parse": "разбор",
    "parsing": "синтаксический разбор",
    "patch": "патч",
    "patching": "патчинг",
    "performance": "производительность",
    "persistent memory": "постоянная память",
    "php": "PHP",
    "phrase tag": "фразовый тег",
    "pickling": "сериализация pickle",
    "pipe": "канал",
    "pipeline": "конвейер",
    "pixel shader": "пиксельный шейдер",
    "pointer": "указатель",
    "polymorphism": "полиморфизм",
    "pop": "снятие со стека",
    "portable language": "переносимый язык",
    "positional parameter": "позиционный параметр",
    "print": "печать",
    "private": "закрытый",
    "private variable": "закрытая переменная",
    "problem": "задача",
    "procedural language": "процедурный язык",
    "procedural programming": "процедурное программирование",
    "procedure": "процедура",
    "program": "программа",
    "program generator": "генератор программ",
    "program language": "язык программ",
    "program listing": "листинг",
    "programmable": "программируемый",
    "programmer": "программист",
    "programming": "программирование",
    "programming conditional statement": "условный оператор",
    "programming in logic": "программирование в логике",
    "programming interface": "программный интерфейс",
    "programming language": "язык программирования",
    "programming language and variation": "язык программирования и вариант",
    "programming language paradigm": "парадигма языка программирования",
    "programming paradigm": "парадигма программирования",
    "programming technique": "техника программирования",
    "programming tool": "инструмент программирования",
    "properties": "свойства",
    "property": "свойство",
    "protocol": "протокол",
    "pseudo-class": "псевдокласс",
    "pseudo-operation": "псевдооперация",
    "pseudocode": "псевдокод",
    "pseudorandom": "псевдослучайный",
    "public": "открытый",
    "pull": "вытягивание",
    "punctuation mark": "знак препинания",
    "push": "помещение в стек",
    "python": "Python",
    "pythonic": "питонический",
    "quality attribute": "атрибут качества",
    "query language": "язык запросов",
    "querying": "запрашивание",
    "queue": "очередь",
    "quick-and-dirty": "на скорую руку",
    "race condition": "гонка",
    "random": "случайный",
    "random seed": "зерно ГСЧ",
    "range": "диапазон",
    "rank": "ранг",
    "recompile": "перекомпиляция",
    "record": "запись",
    "recursion": "рекурсия",
    "recursive": "рекурсивный",
    "regex": "регулярное выражение",
    "relational algebra": "реляционная алгебра",
    "relational database": "реляционная БД",
    "release": "релиз",
    "reliability": "надёжность",
    "repeat counter": "счётчик повторений",
    "repetition": "повторение",
    "repl": "интерактивный цикл",
    "repository": "репозиторий",
    "request": "запрос",
    "reserved character": "зарезервированный символ",
    "response": "ответ",
    "return address": "адрес возврата",
    "return statement": "оператор возврата",
    "reverse engineering": "обратная разработка",
    "router": "маршрутизатор",
    "routing algorithm": "алгоритм маршрутизации",
    "ruby": "Ruby",
    "run time": "время выполнения",
    "runtime environment": "среда выполнения",
    "runtime error": "ошибка времени выполнения",
    "s-expression": "s-выражение",
    "safe font": "безопасный шрифт",
    "sandbox": "песочница",
    "scalability": "масштабируемость",
    "scalar": "скаляр",
    "schema matching": "сопоставление схем",
    "scheme programming language": "язык Scheme",
    "script": "сценарий",
    "scripting language": "язык сценариев",
    "sdk": "набор средств разработки",
    "second generation language": "язык второго поколения",
    "security": "безопасность",
    "segfault": "ошибка сегментации",
    "semantics": "семантика",
    "semaphore": "семафор",
    "separator": "разделитель",
    "sequence": "последовательность",
    "server": "сервер",
    "server-side": "серверная сторона",
    "server-side scripting": "серверные сценарии",
    "servlet": "сервлет",
    "shebang": "шебанг",
    "shell": "оболочка",
    "shift": "сдвиг",
    "short-circuit operator": "сокращённое вычисление",
    "signedness": "знаковость",
    "simple sorting technique": "простая сортировка",
    "simulated annealing": "имитация отжига",
    "single step": "пошагово",
    "snippet": "фрагмент кода",
    "soap": "SOAP",
    "socket": "сокет",
    "software": "программное обеспечение",
    "software architecture": "архитектура ПО",
    "software compiler": "компилятор ПО",
    "software component": "компонент ПО",
    "software development method": "метод разработки ПО",
    "software development phases": "фазы разработки ПО",
    "software engineering": "программная инженерия",
    "software interface": "программный интерфейс",
    "software library": "библиотека ПО",
    "source": "источник",
    "source code": "исходный код",
    "spaghetti code": "спагетти-код",
    "special purpose language": "язык специального назначения",
    "specification": "спецификация",
    "spooling": "спулинг",
    "sql": "SQL",
    "sqlite": "SQLite",
    "stack": "стек",
    "stack pointer": "указатель стека",
    "standard": "стандарт",
    "standard attribute": "стандартный атрибут",
    "statement": "оператор",
    "stdin": "стандартный ввод",
    "stream processing": "потоковая обработка",
    "string": "строка",
    "strongly typed language": "строго типизированный язык",
    "stubroutine": "заглушка",
    "style": "стиль",
    "style sheet language": "язык таблиц стилей",
    "stylesheet": "таблица стилей",
    "submit": "отправка",
    "subroutine": "подпрограмма",
    "subscript": "нижний индекс",
    "subset": "подмножество",
    "substring": "подстрока",
    "subtract": "вычитание",
    "subversion": "Subversion",
    "superclass": "надкласс",
    "swift": "Swift",
    "switch": "коммутатор",
    "switch statement": "оператор switch",
    "syntactic sugar": "синтаксический сахар",
    "syntax": "синтаксис",
    "syntax error": "синтаксическая ошибка",
    "system administrator": "системный администратор",
    "system analysis": "системный анализ",
    "system analyst": "системный аналитик",
    "system development": "разработка систем",
    "system software": "системное ПО",
    "systems engineer": "системный инженер",
    "table": "таблица",
    "tail recursion": "хвостовая рекурсия",
    "tech stack": "стек технологий",
    "technique": "техника",
    "technique in software development": "техника разработки ПО",
    "technology or approach": "технология или подход",
    "ternary": "тернарный",
    "ternary operator": "тернарный оператор",
    "tessellation": "тесселяция",
    "tester": "тестировщик",
    "testing": "тестирование",
    "theoretical computer science": "теоретическая информатика",
    "third-generation programming language": "язык третьего поколения",
    "thread": "поток",
    "token": "токен",
    "tool": "инструмент",
    "transaction": "транзакция",
    "transcompiler": "транскомпилятор",
    "true": "истина",
    "trunk": "ствол",
    "tuple": "кортеж",
    "turing completeness": "полнота по Тьюрингу",
    "unary operator": "унарный оператор",
    "undefined": "неопределено",
    "undefined variable": "неопределённая переменная",
    "underflow": "потеря значимости",
    "unescape": "снятие экранирования",
    "unicase": "единый регистр",
    "unit test": "модульный тест",
    "unit testing": "модульное тестирование",
    "unshift": "вставка в начало",
    "usability": "юзабилити",
    "usage": "использование",
    "value": "значение",
    "variable": "переменная",
    "variable expression": "выражение с переменной",
    "variable-length field": "поле переменной длины",
    "version": "версия",
    "version control": "контроль версий",
    "version control system": "система контроля версий",
    "vibe coding": "вайб-кодинг",
    "visual studio": "Visual Studio",
    "void": "пустой тип",
    "waterfall model": "каскадная модель",
    "web application": "веб-приложение",
    "web development": "веб-разработка",
    "web server": "веб-сервер",
    "what is bit flip?": "инверсия бита",
    "what is line height?": "межстрочный интервал",
    "what is pdf converter?": "конвертер PDF",
    "what is the information age?": "информационная эпоха",
    "while": "цикл while",
    "while loop": "цикл while",
    "whole number": "целое число",
    "wide character": "широкий символ",
    "windows driver kit": "набор драйверов Windows",
    "windows server": "Windows Server",
    "workspace": "рабочее пространство",
    "workstation": "рабочая станция",
    "xml": "XML",
    "xor operator": "исключающее ИЛИ",
    "xsl": "XSL",
    "xslt": "XSLT",
    "yaml": "YAML",
    "y combinator": "Y-комбинатор",
    "z-buffering": "z-буферизация",
    "zombie": "зомби-процесс",
    "absolute address": "абсолютный адрес",
    "absolute coding": "абсолютное кодирование",
    "access violation": "нарушение доступа",
    "action statement": "оператор действия",
    "actionScript": "ActionScript",
    "activeX": "ActiveX",
    "adaptive technology": "адаптивная технология",
    "add": "сложение",
    "ado": "ADO",
    "advanced SCSI programming interface": "расширенный SCSI-интерфейс",
    "aggregate": "агрегат",
    "agile development methods": "гибкие методы разработки",
    "alert": "оповещение",
    "allocate": "выделение",
    "ambient occlusion": "затенение окружающей среды",
    "apk": "пакет Android",
    "applet": "апплет",
    "application software": "прикладное ПО",
    "approach": "подход",
    "argument": "аргумент",
    "arithmetic": "арифметика",
    "arithmetic operator": "арифметический оператор",
    "array": "массив",
    "array of pointers": "массив указателей",
    "ascii": "ASCII",
    "asm": "язык ассемблера",
    "asp": "активные серверные страницы",
    "assembler": "ассемблер",
    "assembly language": "язык ассемблера",
    "assignment": "присваивание",
    "associative operation": "ассоциативная операция",
    "automated unit testing": "автоматизированное модульное тестирование",
    "automata-based programming": "автоматное программирование",
    "automation": "автоматизация",
    "availability": "доступность",
    "back-face culling": "отсечение нелицевых граней",
    "backend": "серверная часть",
    "background thread": "фоновый поток",
    "backpropagation neural network": "сеть обратного распространения",
    "backup": "резервное копирование",
    "base address": "базовый адрес",
    "batch file": "пакетный файл",
    "binary search": "двоичный поиск",
    "bind": "привязка",
    "bit shift": "сдвиг битов",
    "bitwise operation": "побитовая операция",
    "bitwise operator": "побитовый оператор",
    "block": "блок",
    "block-based programming": "блочное программирование",
    "block-level element": "элемент блочного уровня",
    "boolean": "логический",
    "bracket": "скобка",
    "branch": "ветка",
    "browse": "просмотр",
    "bubble sort": "пузырьковая сортировка",
    "bug": "дефект",
    "bug tracking": "учёт дефектов",
    "build": "сборка",
    "build computer": "сборочный компьютер",
    "bytecode": "байт-код",
    "c": "Си",
    "c#": "C#",
    "c++": "C++",
    "call": "вызов",
    "callback": "обратный вызов",
    "camelcase": "CamelCase",
    "capture": "захват",
    "cell style": "стиль ячейки",
    "cgi": "CGI",
    "chaos model": "модель хаоса",
    "character": "символ",
    "character code": "код символа",
    "circuit satisfiability problem": "выполнимость схемы",
    "class": "класс",
    "classification": "классификация",
    "classpath": "путь классов",
    "client": "клиент",
    "closure": "замыкание",
    "clr": "общеязыковая среда выполнения",
    "cocoa": "Cocoa",
    "code": "код",
    "code block": "блок кода",
    "code page": "кодовая страница",
    "code refactoring": "рефакторинг кода",
    "coding": "кодирование",
    "coffeescript": "CoffeeScript",
    "collaborative programming": "совместное программирование",
    "collection": "коллекция",
    "combination": "сочетание",
    "command": "команда",
    "command language": "командный язык",
    "comment": "комментарий",
    "commit": "фиксация",
    "commutative operation": "коммутативная операция",
    "compilation": "компиляция",
    "compile": "компиляция",
    "compiler": "компилятор",
    "compiler infrastructure": "инфраструктура компилятора",
    "complementarity": "дополнительность",
    "component": "компонент",
    "compute": "вычисление",
    "computer designated": "назначенный компьютер",
    "computer error": "ошибка компьютера",
    "computer instructions": "инструкции компьютера",
    "computer language": "компьютерный язык",
    "computer network": "компьютерная сеть",
    "computer program": "компьютерная программа",
    "computer programming algorithm": "алгоритм программирования",
    "computer programming language": "язык программирования",
    "computer programming paradigm": "парадигма программирования",
    "computer science": "информатика",
    "computing process": "вычислительный процесс",
    "concat": "конкатенация",
    "concurrency": "параллелизм",
    "condition": "условие",
    "conditional block": "условный блок",
    "conditional expression": "условное выражение",
    "conditional statement": "условный оператор",
    "confidentiality": "конфиденциальность",
    "constant": "константа",
    "constructor": "конструктор",
    "constructor chaining": "цепочка конструкторов",
    "container": "контейнер",
    "containerization": "контейнеризация",
    "content migration": "миграция контента",
    "control flow": "управление потоком",
    "control parameter": "управляющий параметр",
    "css": "CSS",
    "css compressor": "сжиматель CSS",
    "css editor": "редактор CSS",
    "csv": "CSV",
    "curly bracket": "фигурная скобка",
    "data": "данные",
    "data file": "файл данных",
    "data flow diagram": "диаграмма потоков данных",
    "data format": "формат данных",
    "data loss": "потеря данных",
    "data source": "источник данных",
    "data structure": "структура данных",
    "data type": "тип данных",
    "data-flow analysis": "анализ потока данных",
    "database": "база данных",
    "database server": "сервер БД",
    "database system": "СУБД",
    "database table": "таблица БД",
    "database terms": "термины БД",
    "dataflow programming": "потоковая парадигма",
    "datalog": "Datalog",
    "dead code": "мёртвый код",
    "debug": "отладка",
    "debugger": "отладчик",
    "debugging": "отладка",
    "declaration": "объявление",
    "declarative programming": "декларативное программирование",
    "decompiler": "декомпилятор",
    "decrement": "декремент",
    "deductive database": "дедуктивная база",
    "delimiter": "разделитель",
    "demote": "понижение",
    "dense matrix": "плотная матрица",
    "dependent variable": "зависимая переменная",
    "deployment": "развёртывание",
    "deprecated": "устаревший",
    "dereference operator": "оператор разыменования",
    "desktop application": "настольное приложение",
    "developer": "разработчик",
    "development": "разработка",
    "development tool": "средство разработки",
    "device driver": "драйвер устройства",
    "devops": "DevOps",
    "dhtml": "динамический HTML",
    "dialect": "диалект",
    "die": "аварийное завершение",
    "diff": "разность файлов",
    "disassembler": "дизассемблер",
    "discrete optimization": "дискретная оптимизация",
    "div": "деление / блок div",
    "django": "Django",
    "dml": "язык манипулирования данными",
    "do": "цикл do",
    "docker": "Docker",
    "dom": "объектная модель документа",
    "dragon book": "книга дракона",
    "dump": "дамп",
    "dword": "двойное слово",
    "dynamic binding": "динамическое связывание",
    "dynamic dump": "динамический дамп",
    "eclipse": "Eclipse",
    "ecmascript": "ECMAScript",
    "eight queens problem": "задача восьми ферзей",
    "element": "элемент",
    "elixir": "Elixir",
    "ellipsis": "многоточие",
    "else": "иначе",
    "else if": "иначе-если",
    "embedded java": "встраиваемая Java",
    "encode": "кодирование",
    "encoding": "кодировка",
    "encryption": "шифрование",
    "end user": "конечный пользователь",
    "endian": "порядок байтов",
    "endless loop": "бесконечный цикл",
    "eof": "конец файла",
    "epoch": "эпоха",
    "eq": "равно",
    "equ": "эквивалентность",
    "equal": "равенство",
    "erlang": "Erlang",
    "error": "ошибка",
    "errorlevel": "код ошибки",
    "escape sequence": "escape-последовательность",
    "eval": "вычисление",
    "event": "событие",
    "event listener": "обработчик события",
    "event-driven programming": "событийное программирование",
    "exception": "исключение",
    "exception handling": "обработка исключений",
    "exec": "исполнение",
    "executable": "исполняемый файл",
    "execution": "выполнение",
    "exists": "существует",
    "exit status": "код выхода",
    "exponent": "показатель",
    "exponential backoff": "экспоненциальная пауза",
    "expression": "выражение",
    "f programming language": "язык F",
    "f#": "F#",
    "factorial": "факториал",
    "failure": "отказ",
    "false": "ложь",
    "false positive": "ложная тревога",
    "feature": "функция-свойство",
    "feature complete": "функционально завершённый",
    "fifth generation language": "язык пятого поколения",
    "file": "файл",
    "file format": "формат файла",
    "firewall": "межсетевой экран",
    "firmware": "прошивка",
    "first generation language": "язык первого поколения",
    "first-class object": "объект первого класса",
    "flag": "флаг",
    "flat file": "плоский файл",
    "floating-point": "плавающая точка",
    "foo": "фиктивный объект",
    "for": "для",
    "for loop": "цикл for",
    "foreach": "цикл foreach",
    "foreign key": "внешний ключ",
    "formal language": "формальный язык",
    "forth": "Форт",
    "fortran": "Фортран",
    "fourth generation language": "язык четвёртого поколения",
    "framework": "фреймворк",
    "frontend": "клиентская часть",
    "full stack developer": "полный стек-разработчик",
    "function": "функция",
    "function call": "вызов функции",
    "functional language": "функциональный язык",
    "functional programming": "функциональное программирование",
    "functional programming language": "функциональный язык программирования",
    "fuzz testing": "фаззинг",
    "game of life": "игра «Жизнь»",
    "gang of four": "банда четырёх",
    "garbage collection": "сборка мусора",
    "gaussian pyramid": "пирамида Гаусса",
    "gcc": "коллекция компиляторов GNU",
    "general-purpose language": "язык общего назначения",
    "genetic programming": "генетическое программирование",
    "git": "Git",
    "github": "GitHub",
    "glitch": "глюк",
    "glob": "шаблон имён",
    "global variable": "глобальная переменная",
    "glue code": "связующий код",
    "go": "Go",
    "golang": "Go",
    "goto": "переход",
    "gpl": "универсальная общественная лицензия GNU",
    "graphical representation": "графическое представление",
    "greedy": "жадный",
    "hackathon": "хакатон",
    "halting problem": "проблема остановки",
    "hard code": "жёсткое кодирование",
    "hardware": "аппаратное обеспечение",
    "hash": "хеш",
    "hash table": "хеш-таблица",
    "haskell": "Haskell",
    "heap": "куча",
    "hello world": "пример hello world",
    "heroku": "Heroku",
    "heuristic evaluation": "эвристическая оценка",
    "hex editor": "шестнадцатеричный редактор",
    "high-level language": "язык высокого уровня",
    "high-level programming language": "высокоуровневый ЯП",
    "html": "HTML",
    "human error": "человеческая ошибка",
    "hungarian notation": "венгерская запись",
    "ide": "среда разработки",
    "idempotence": "идемпотентность",
    "identifier": "идентификатор",
    "if": "если",
    "if else": "если-иначе",
    "if statement": "оператор if",
    "immutable object": "неизменяемый объект",
    "imperative programming": "императивное программирование",
    "implicit parallelism": "неявный параллелизм",
    "increment": "инкремент",
    "indirect address": "косвенный адрес",
    "information object": "информационный объект",
    "inherent error": "внутренне присущая ошибка",
    "inheritance": "наследование",
    "inline": "встроенный",
    "input stream": "входной поток",
    "input/output statement": "оператор ввода-вывода",
    "instance": "экземпляр",
    "instantiation": "создание экземпляра",
    "integer": "целое",
    "integrity": "целостность",
    "intellij idea": "IntelliJ IDEA",
    "interface specification": "спецификация интерфейса",
    "intermediate language": "промежуточный язык",
    "interpretation": "интерпретация",
    "interpreted": "интерпретируемый",
    "interpreter": "интерпретатор",
    "invalid": "недопустимый",
    "ipc": "межпроцессное взаимодействие",
    "it role": "роль в IT",
    "iteration": "итерация",
    "java": "Java",
    "java champion": "чемпион Java",
    "java ee": "Java EE",
    "java me": "Java ME",
    "java native interface": "JNI",
    "java reserved words": "зарезервированные слова Java",
    "javascript": "JavaScript",
    "jdbc": "JDBC",
    "jdk": "JDK",
    "jenkins": "Jenkins",
    "jit": "компиляция на лету",
    "jre": "среда выполнения Java",
    "json": "JSON",
    "jsp": "страницы Java-сервера",
    "julia": "Julia",
    "jupyter": "Jupyter",
    "jvm": "виртуальная машина Java",
    "keyword": "ключевое слово",
    "kit": "набор",
    "kludge": "костыль",
    "kotlin": "Kotlin",
    "kubernetes": "Kubernetes",
    "label": "метка",
    "lambda calculus": "лямбда-исчисление",
    "langchain": "LangChain",
    "language": "язык",
    "language construct": "конструкция языка",
    "language processor": "процессор языка",
    "large language model": "большая языковая модель",
    "large quantity": "большое количество",
    "lexical analysis": "лексический анализ",
    "lexicon": "лексикон",
    "library": "библиотека",
    "lifecycle": "жизненный цикл",
    "link time": "время компоновки",
    "linked list": "связный список",
    "linker": "компоновщик",
    "linking": "компоновка",
    "linux": "Linux",
    "lisp": "Лисп",
    "literal": "литерал",
    "llvm": "LLVM",
    "local optimum": "локальный оптимум",
    "log file": "файл журнала",
    "logic programming": "логическое программирование",
    "logic programming language": "язык логического программирования",
    "logical operation": "логическая операция",
    "logical operator": "логический оператор",
    "lookup table": "таблица поиска",
    "loop": "цикл",
    "loophole": "лазейка",
    "loosely typed language": "слабо типизированный язык",
    "low-code": "low-code",
    "low-level language": "низкоуровневый язык",
    "low-level programming language": "низкоуровневый ЯП",
    "lua": "Lua",
    "machine language": "машинный код",
    "macos": "macOS",
    "magic quotes": "магические кавычки",
    "maintainability": "сопровождаемость",
    "maintenance": "сопровождение",
    "map": "отображение",
    "markup language": "язык разметки",
    "math": "математика",
    "math operation": "математическая операция",
    "mathematical operation": "математическая операция",
    "matlab": "MATLAB",
    "matrix": "матрица",
    "memoization": "мемоизация",
    "memory": "память",
    "mercurial": "Mercurial",
    "meta": "мета",
    "meta tag": "метатег",
    "metacharacter": "метасимвол",
    "metaclass": "метакласс",
    "metalanguage": "метаязык",
    "method": "метод",
    "method overloading": "перегрузка методов",
    "middleware": "промежуточное ПО",
    "mobile application": "мобильное приложение",
    "mod": "остаток от деления",
    "model": "модель",
    "modular programming": "модульное программирование",
    "module": "модуль",
    "monitoring": "мониторинг",
    "monkey testing": "хаотическое тестирование",
    "monte carlo method": "метод Монте-Карло",
    "msdn": "сеть разработчиков Microsoft",
    "msvc": "Microsoft Visual C++",
    "multi-paradigm programming language": "мультипарадигмальный ЯП",
    "multi-pass compiler": "многопроходный компилятор",
    "multiply": "умножение",
    "mutex": "мьютекс",
    "nan": "не число",
    "native compiler": "нативный компилятор",
    "native language": "родной язык",
    "natural language": "естественный язык",
    "nbsp": "неразрывный пробел",
    "nda": "соглашение о неразглашении",
    "nest": "вложение",
    "nested loops join": "соединение вложенными циклами",
    "netlify": "Netlify",
    "network device": "сетевое устройство",
    "nil pointer": "нулевой указатель",
    "nim": "Nim",
    "no operation instructions": "пустые инструкции",
    "no-code": "без кода",
    "node.js": "Node.js",
    "nodelist": "список узлов",
    "non-contiguous data structure": "несвязная структура данных",
    "nonexecutable statement": "неисполняемый оператор",
    "nosql database": "база NoSQL",
    "null": "нуль",
    "null character": "нуль-символ",
    "numpy": "NumPy",
    "obfuscated code": "запутанный код",
    "object": "объект",
    "object code": "объектный код",
    "object file": "объектный файл",
    "object module": "объектный модуль",
    "object-oriented": "объектно-ориентированный",
    "object-oriented language": "ОО-язык",
    "object-oriented programming": "объектно-ориентированное программирование",
    "object-oriented programming language": "ОО-язык программирования",
    "object-oriented version": "ОО-версия",
    "objective-c": "Objective-C",
    "ocaml": "OCaml",
    "octave": "GNU Octave",
    "odbc": "ODBC",
    "one-pass compiler": "однопроходный компилятор",
    "onmouseover": "наведение мыши",
    "opcode": "код операции",
    "open source scripting language": "открытый скриптовый язык",
    "open-source version control system": "открытая СКВ",
    "opengl polygon": "полигон OpenGL",
    "operand": "операнд",
    "operating system": "операционная система",
    "operation": "операция",
    "operator": "оператор",
    "operator associatively": "ассоциативность операторов",
    "operator precedence": "приоритет операторов",
    "or operator": "оператор ИЛИ",
    "orchestration": "оркестрация",
    "order of operations": "порядок операций",
    "overflow error": "ошибка переполнения",
    "overload": "перегрузка",
    "p-code": "п-код",
    "package": "пакет",
    "paradigm": "парадигма",
    "parameter": "параметр",
    "parenthesis": "круглые скобки",
    "parse": "разбор",
    "parsing": "разбор",
    "pascal": "Паскаль",
    "pastebin": "вставка кода",
    "patch": "заплатка",
    "patching": "наложение заплаток",
    "performance": "производительность",
    "perl": "Perl",
    "persistent memory": "стойкая память",
    "php": "PHP",
    "phrase tag": "фразовый тег",
    "pickling": "сериализация",
    "pipe": "канал",
    "pipeline": "конвейер",
    "pixel shader": "пиксельный шейдер",
    "pointer": "указатель",
    "polymorphism": "полиморфизм",
    "pop": "извлечение",
    "portable language": "переносимый язык",
    "positional parameter": "позиционный параметр",
    "print": "печать",
    "printf": "форматный вывод",
    "private": "закрытый",
    "private variable": "закрытая переменная",
    "problem": "задача",
    "procedural language": "процедурный язык",
    "procedural programming": "процедурное программирование",
    "procedure": "процедура",
    "program": "программа",
    "program generator": "генератор программ",
    "program language": "язык программ",
    "program listing": "листинг программы",
    "programmable": "программируемый",
    "programmer": "программист",
    "programming": "программирование",
    "programming conditional statement": "условный оператор",
    "programming in logic": "логическое программирование",
    "programming interface": "программный интерфейс",
    "programming language": "язык программирования",
    "programming language and variation": "язык программирования и вариант",
    "programming language paradigm": "парадигма языка",
    "programming paradigm": "парадигма программирования",
    "programming technique": "приём программирования",
    "programming tool": "инструмент программирования",
    "prolog": "Пролог",
    "properties": "свойства",
    "property": "свойство",
    "protocol": "протокол",
    "pseudo-class": "псевдокласс",
    "pseudo-operation": "псевдооперация",
    "pseudocode": "псевдокод",
    "pseudorandom": "псевдослучайный",
    "public": "открытый",
    "pull": "вытягивание",
    "punctuation mark": "знак препинания",
    "purebasic": "PureBasic",
    "push": "помещение",
    "python": "Python",
    "pythonic": "в духе Python",
    "quality attribute": "атрибут качества",
    "query language": "язык запросов",
    "querying": "запросы",
    "queue": "очередь",
    "quick-and-dirty": "на скорую руку",
    "qword": "четверное слово",
    "r programming language": "язык R",
    "race condition": "состояние гонки",
    "racket": "Racket",
    "rad": "быстрая разработка",
    "random": "случайный",
    "random seed": "зерно случайности",
    "range": "диапазон",
    "rank": "ранг",
    "rdf": "RDF",
    "react": "React",
    "react native": "React Native",
    "real number": "действительное число",
    "recompile": "перекомпиляция",
    "record": "запись",
    "recursion": "рекурсия",
    "recursive": "рекурсивный",
    "recursive mathematical function": "рекурсивная математическая функция",
    "regex": "регулярное выражение",
    "relational algebra": "реляционная алгебра",
    "relational database": "реляционная база данных",
    "release": "выпуск",
    "reliability": "надёжность",
    "rem": "комментарий REM",
    "repeat counter": "счётчик повторений",
    "repetition": "повторение",
    "repl": "цикл REPL",
    "repository": "репозиторий",
    "request": "запрос",
    "reserved character": "зарезервированный символ",
    "response": "ответ",
    "return address": "адрес возврата",
    "return statement": "оператор возврата",
    "reverse engineering": "обратная инженерия",
    "router": "маршрутизатор",
    "routing algorithm": "алгоритм маршрутизации",
    "rpg": "RPG",
    "ruby": "Ruby",
    "run time": "время выполнения",
    "runtime environment": "среда выполнения",
    "runtime error": "ошибка выполнения",
    "rust": "Rust",
    "s-expression": "s-выражение",
    "safe font": "безопасный шрифт",
    "sandbox": "песочница",
    "scala": "Scala",
    "scalability": "масштабируемость",
    "scalar": "скаляр",
    "scanf": "форматный ввод",
    "schema matching": "сопоставление схем",
    "scheme programming language": "Scheme",
    "scratch": "Scratch",
    "script": "сценарий",
    "scripting language": "скриптовый язык",
    "sdk": "набор разработки",
    "second generation language": "язык второго поколения",
    "security": "безопасность",
    "security descriptor definition language": "язык дескрипторов безопасности",
    "segfault": "ошибка сегментации",
    "semantics": "семантика",
    "semaphore": "семафор",
    "separator": "разделитель",
    "sequence": "последовательность",
    "server": "сервер",
    "server-side": "на стороне сервера",
    "server-side scripting": "серверные сценарии",
    "servlet": "сервлет",
    "sgml": "SGML",
    "shebang": "шебанг",
    "shell": "оболочка",
    "shift": "сдвиг",
    "short-circuit operator": "сокращённый оператор",
    "signedness": "знаковость",
    "simple sorting technique": "простой метод сортировки",
    "simula": "Симула",
    "simulated annealing": "имитация отжига",
    "single step": "пошаговое выполнение",
    "smalltalk": "Smalltalk",
    "smil": "SMIL",
    "snippet": "фрагмент кода",
    "soap": "SOAP",
    "socket": "сокет",
    "soft": "программный",
    "software": "программное обеспечение",
    "software architecture": "архитектура ПО",
    "software compiler": "компилятор",
    "software component": "компонент ПО",
    "software development method": "метод разработки ПО",
    "software development phases": "фазы разработки ПО",
    "software engineering": "программная инженерия",
    "software interface": "программный интерфейс",
    "software library": "программная библиотека",
    "source": "источник",
    "source code": "исходный код",
    "sourceforge": "SourceForge",
    "spaghetti code": "спагетти-код",
    "special purpose language": "узкоспециальный язык",
    "specification": "спецификация",
    "spooling": "спулинг",
    "sql": "SQL",
    "sqlite": "SQLite",
    "stack": "стек",
    "stack pointer": "указатель стека",
    "standard": "стандарт",
    "standard attribute": "стандартный атрибут",
    "statement": "оператор",
    "stdin": "стандартный ввод",
    "stl": "стандартная библиотека шаблонов",
    "stream processing": "потоковая обработка",
    "string": "строка",
    "strongly typed language": "строго типизированный язык",
    "stubroutine": "заглушка",
    "style": "стиль",
    "style sheet language": "язык таблиц стилей",
    "stylesheet": "таблица стилей",
    "submit": "отправка",
    "subroutine": "подпрограмма",
    "subscript": "индекс",
    "subset": "подмножество",
    "substring": "подстрока",
    "subtract": "вычитание",
    "subversion": "Subversion",
    "superclass": "суперкласс",
    "swift": "Swift",
    "switch": "коммутатор",
    "switch statement": "оператор switch",
    "syntactic sugar": "синтаксический сахар",
    "syntax": "синтаксис",
    "syntax error": "синтаксическая ошибка",
    "system administrator": "системный администратор",
    "system analysis": "системный анализ",
    "system analyst": "системный аналитик",
    "system development": "разработка систем",
    "system software": "системное ПО",
    "systems engineer": "системный инженер",
    "table": "таблица",
    "tail recursion": "хвостовая рекурсия",
    "tcl": "Tcl",
    "tech stack": "стек технологий",
    "technique": "техника",
    "technique in software development": "техника разработки ПО",
    "technology or approach": "технология или подход",
    "ternary": "тернарный",
    "ternary operator": "тернарный оператор",
    "tessellation": "тесселяция",
    "tester": "тестировщик",
    "testing": "тестирование",
    "theoretical computer science": "теоретическая информатика",
    "third-generation programming language": "язык третьего поколения",
    "thread": "поток",
    "thunk": "thunk",
    "token": "лексема",
    "tool": "инструмент",
    "toolbox": "набор инструментов",
    "transaction": "транзакция",
    "transcompiler": "транскомпилятор",
    "true": "истина",
    "true basic": "True BASIC",
    "trunk": "основная ветвь",
    "tuple": "кортеж",
    "turbo pascal": "Turbo Pascal",
    "turing completeness": "полнота по Тьюрингу",
    "uint8": "беззнаковое 8-битное",
    "unary operator": "унарный оператор",
    "undefined": "неопределённое",
    "undefined variable": "неопределённая переменная",
    "underflow": "антипереполнение",
    "unescape": "снятие экранирования",
    "unicase": "единый регистр",
    "unit test": "модульный тест",
    "unit testing": "модульное тестирование",
    "unity": "Unity",
    "unreal engine": "Unreal Engine",
    "unshift": "вставка в начало",
    "usability": "удобство использования",
    "usage": "использование",
    "value": "значение",
    "var": "переменная",
    "variable": "переменная",
    "variable expression": "выражение с переменной",
    "variable-length field": "поле переменной длины",
    "vb": "Visual Basic",
    "vbscript": "VBScript",
    "version": "версия",
    "version control": "управление версиями",
    "version control system": "система управления версиями",
    "vhdl": "VHDL",
    "vibe coding": "вайб-кодинг",
    "vim": "Vim",
    "visual": "визуальный",
    "visual studio": "Visual Studio",
    "void": "пустой тип",
    "vue": "Vue",
    "w3schools": "W3Schools",
    "wasm": "WebAssembly",
    "waterfall model": "каскадная модель",
    "web application": "веб-приложение",
    "web development": "веб-разработка",
    "web server": "веб-сервер",
    "webgl": "WebGL",
    "what is bit flip?": "инверсия бита",
    "what is line height?": "высота строки",
    "what is pdf converter?": "конвертер PDF",
    "what is the information age?": "информационная эпоха",
    "while": "пока",
    "while loop": "цикл while",
    "whole number": "целое число",
    "wide character": "широкий символ",
    "windows driver kit": "набор драйверов Windows",
    "windows server": "Windows Server",
    "wml": "беспроводной язык разметки",
    "workspace": "рабочая область",
    "workstation": "рабочая станция",
    "xml": "XML",
    "xna": "XNA",
    "xor operator": "исключающее ИЛИ",
    "xoxo": "XOXO",
    "xsl": "XSL",
    "xslt": "XSLT",
    "y combinator": "комбинатор Y",
    "yaml": "YAML",
    "z-buffering": "z-буферизация",
    "zombie": "зомби-процесс",
    ".net": ".NET",
    "/n": "перевод строки",
    "/r": "возврат каретки",
    "a-0": "A-0",
    "abend": "аварийное завершение",
    "acid": "ACID",
    "acm": "ACM",
    "ada": "Ада",
    "algol": "Алгол",
    "altair basic": "Altair BASIC",
    "aop": "аспектно-ориентированное программирование",
    "api": "программный интерфейс",
    "apk": "пакет Android",
    "asp": "активные серверные страницы",
    "ats": "система отслеживания кандидатов",
    "autohotkey": "AutoHotkey",
    "babel": "Babel",
    "basic": "Бейсик",
    "bcpl": "BCPL",
    "beanshell": "BeanShell",
    "brooks": "Брукс",
    "bugfairy": "сказочная ошибка",
    "c": "Си",
    "camel book": "верблюжья книга",
    "cc": "CC",
    "chaos model": "модель хаоса",
    "clojure": "Clojure",
    "clos": "CLOS",
    "clr": "CLR",
    "cobol": "Кобол",
    "cocoa": "Cocoa",
    "coffeescript": "CoffeeScript",
    "cpan": "архив Perl",
    "cpl": "CPL",
    "css": "каскадные таблицы стилей",
    "csv": "CSV",
    "curry": "Карри",
    "cvs": "CVS",
    "cygwin": "Cygwin",
    "d": "D",
    "darkbasic": "DarkBASIC",
    "dart": "Dart",
    "datalog": "Datalog",
    "dde": "DDE",
    "ddk": "набор драйверов",
    "dev home": "Dev Home",
    "devops": "DevOps",
    "dhtml": "динамический HTML",
    "django": "Django",
    "dml": "язык манипулирования данными",
    "docker": "Docker",
    "dom": "объектная модель документа",
    "dragon book": "книга дракона",
    "dribbleware": "недоделанное ПО",
    "dylan programming language": "Dylan",
    "eclipse": "Eclipse",
    "ecmascript": "ECMAScript",
    "elixir": "Elixir",
    "erlang": "Erlang",
    "f#": "F#",
    "f programming language": "язык F",
    "forth": "Форт",
    "fortran": "Фортран",
    "gcc": "GCC",
    "git": "Git",
    "github": "GitHub",
    "go": "Go",
    "golang": "Go",
    "googolplex": "гуголплекс",
    "gpl": "лицензия GNU GPL",
    "grasshopper": "Grasshopper",
    "gtk": "GTK",
    "gw-basic": "GW-BASIC",
    "hal": "HAL",
    "haskell": "Haskell",
    "hdml": "язык разметки портативных устройств",
    "heroku": "Heroku",
    "hiew": "Hiew",
    "html": "HTML",
    "hwclock": "аппаратные часы",
    "ide": "среда разработки",
    "intellij idea": "IntelliJ IDEA",
    "io": "Io",
    "ioccc": "конкурс обфусцированного Си",
    "isapi": "ISAPI",
    "java": "Java",
    "javafx": "JavaFX",
    "javascript": "JavaScript",
    "javascriptcore": "JavaScriptCore",
    "javax": "Javax",
    "jbuilder": "JBuilder",
    "jcl": "язык управления заданиями",
    "jdbc": "JDBC",
    "jdk": "JDK",
    "jenkins": "Jenkins",
    "jhtml": "Java в HTML",
    "jil": "промежуточный язык Java",
    "jit": "JIT",
    "jre": "JRE",
    "jscript": "JScript",
    "json": "JSON",
    "jsp": "JSP",
    "jsr": "запрос спецификации Java",
    "julia": "Julia",
    "jupyter": "Jupyter",
    "jvm": "JVM",
    "javac": "компилятор Java",
    "karel": "Karel",
    "kotlin": "Kotlin",
    "kubernetes": "Kubernetes",
    "langchain": "LangChain",
    "lisp": "Лисп",
    "livescript": "LiveScript",
    "llvm": "LLVM",
    "logo": "Лого",
    "lua": "Lua",
    "macos": "macOS",
    "matlab": "MATLAB",
    "mbean": "управляемые бины",
    "mercurial": "Mercurial",
    "metro": "Metro",
    "microsoft basic": "Microsoft BASIC",
    "modula": "Модула",
    "msdn": "MSDN",
    "msvc": "MSVC",
    "mumps": "MUMPS",
    "mysql": "MySQL",
    "netlify": "Netlify",
    "nim": "Nim",
    "nimrod": "Nimrod",
    "node.js": "Node.js",
    "numpy": "NumPy",
    "oberon": "Оберон",
    "objective-c": "Objective-C",
    "ocaml": "OCaml",
    "octave": "Octave",
    "odbc": "ODBC",
    "pascal": "Паскаль",
    "pastebin": "вставка текста",
    "pear": "PEAR",
    "perl": "Perl",
    "personaljava": "PersonalJava",
    "php": "PHP",
    "picojava": "PicoJava",
    "prolog": "Пролог",
    "purebasic": "PureBasic",
    "python": "Python",
    "qt": "Qt",
    "r programming language": "язык R",
    "racket": "Racket",
    "rad": "быстрая разработка приложений",
    "rcs": "RCS",
    "rdf": "RDF",
    "react": "React",
    "react native": "React Native",
    "reia": "Reia",
    "rom basic": "ROM BASIC",
    "ruby": "Ruby",
    "rust": "Rust",
    "scala": "Scala",
    "scheme programming language": "Scheme",
    "scratch": "Scratch",
    "sgml": "SGML",
    "simula": "Симула",
    "smalltalk": "Smalltalk",
    "smil": "SMIL",
    "soap": "SOAP",
    "sourceforge": "SourceForge",
    "sql": "SQL",
    "sqlite": "SQLite",
    "stl": "STL",
    "subversion": "Subversion",
    "swift": "Swift",
    "tcl": "Tcl",
    "tk": "Tk",
    "true basic": "True BASIC",
    "turbo pascal": "Turbo Pascal",
    "udacity": "Udacity",
    "uint8": "UInt8",
    "unity": "Unity",
    "unreal engine": "Unreal Engine",
    "vb": "Visual Basic",
    "vbscript": "VBScript",
    "vhdl": "VHDL",
    "vim": "Vim",
    "visual studio": "Visual Studio",
    "vue": "Vue",
    "w3schools": "W3Schools",
    "wasm": "WebAssembly",
    "wdf": "WDF",
    "webgl": "WebGL",
    "windows server": "Windows Server",
    "wml": "WML",
    "xna": "XNA",
    "xml": "XML",
    "xsl": "XSL",
    "xslt": "XSLT",
    "yaml": "YAML",
    "java ee": "Java EE",
    "java me": "Java ME",
    "javafx": "JavaFX",
    "javax": "пакет javax",
    "jbuilder": "JBuilder",
    "javascriptcore": "ядро JavaScript",
    "jupyter": "Jupyter",
    "np-c": "NP-полный",
    "openGL polygon": "полигон OpenGL",
    "qi": "Qi",
    "rcw": "обёртка COM",
    "s-expression": "s-выражение",
    "thunk": "thunk",
    "toolbox": "набор инструментов",
    "wasm": "WebAssembly",
    "xoxo": "XOXO",
    "camel book": "книга-верблюд",
    "gang of four": "банда четырёх",
    "hello world": "программа-привет",
    "knights of lambda calculus": "рыцари лямбда-исчисления",
    "loony bin": "психбольница (жарг.)",
    "religion of chi": "культ хи",
}

# нормализация ключей
GLOSS = {k.lower(): v for k, v in GLOSS.items()}


def ru_for(nama):
    k = (nama or "").strip()
    if not k:
        return None
    if k.lower() in GLOSS:
        return GLOSS[k.lower()]
    # «What is X?»
    m = re.match(r"(?i)^what is (?:the )?(.*?)\??$", k)
    if m and m.group(1).lower() in GLOSS:
        return GLOSS[m.group(1).lower()]
    return None  # оставим заимствование = nama


def main():
    eng = JnanaEngine()
    eng.cur.execute("SELECT concept_id, term, lang FROM concept_term")
    by = defaultdict(lambda: {"ru": [], "en": []})
    for cid, term, lang in eng.cur.fetchall():
        if lang in ("ru", "en"):
            by[cid][lang].append(term)
    added = loan = 0
    for cid, nama in eng.names.items():
        if eng.concept_u.get(cid) != 3:
            continue
        if by[cid]["ru"]:
            continue
        ru = ru_for(nama)
        if not ru:
            ru = nama  # заимствование
            loan += 1
        have = {t.lower() for t in by[cid]["ru"]}
        if ru.lower() in have:
            continue
        eng.cur.execute(
            "INSERT IGNORE INTO concept_term (concept_id,term,lang) VALUES (%s,%s,'ru')",
            (cid, ru))
        if eng.cur.rowcount:
            added += 1
            tag = "loan" if ru == nama else "tr"
            print(f"  +{tag:4s} {nama:40s}  ru={ru}")
    eng.commit()
    print(f"added {added} (loanwords among them: {loan})")
    finish(eng)
    eng.close()


if __name__ == "__main__":
    main()
