# -*- coding: utf-8 -*-
# Глаголы, партия 3 (561–828)
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, r'G:\Projects\conceptuum')
from jnana_engine import JnanaEngine

P = {'Д':'действие','М':'ментальный процесс','ДВ':'движение','ОБ':'общение',
     'Ф':'физический процесс','ФЗ':'физиологический процесс','П':'познание'}

V = [
('приобрести','to acquire','Д'),('проанализировать','to analyze','М'),
('проверить','to check','П'),('проверять','to check','П'),
('проверяться','to be checked','П'),('провести','to conduct','Д'),
('проводить','to conduct','Д'),('проводиться','to be conducted','Д'),
('продержаться','to hold out','Д'),('продиктовать','to dictate','ОБ'),
('продолжать','to continue','Д'),('проиграть','to lose','Д'),
('произвести','to produce','Д'),('производить','to produce','Д'),
('производиться','to be produced','Д'),('произноситься','to be pronounced','ОБ'),
('пройти','to pass','ДВ'),('проложить','to lay a route','Д'),
('промолвить','to utter','ОБ'),('проникать','to penetrate','Д'),
('проникнуть','to penetrate','Д'),('пропустить','to let through','Д'),
('проработать','to work through','Д'),('просушить','to dry','Д'),
('протекать','to flow','Ф'),('противоречить','to contradict','ОБ'),
('проходить','to pass','ДВ'),('прочитать','to read','Д'),
('проявить','to display','Д'),('проявиться','to manifest itself','Д'),
('проявляться','to manifest itself','Д'),('пытаться','to try','Д'),
('работать','to work','Д'),('равняться','to equal','Д'),
('разбить','to break','Д'),('разбросать','to scatter','Д'),
('развести','to dilute','Д'),('развивать','to develop','Д'),
('развиваться','to develop','Д'),('развёртываться','to unfold','Д'),
('разграничить','to delimit','Д'),('разделить','to divide','Д'),
('разделять','to divide','Д'),('разлагаться','to decompose','Ф'),
('различать','to distinguish','М'),('различаться','to differ','Д'),
('разложить','to lay out','Д'),('размагнититься','to become demagnetized','Ф'),
('размножаться','to multiply','ФЗ'),('разниться','to vary','Д'),
('разобрать','to analyze','М'),('разобраться','to figure out','М'),
('разрабатываться','to be developed','Д'),('разработать','to develop','Д'),
('разредить','to thin out','Д'),('разрезать','to cut','Д'),
('разрешить','to resolve','Д'),('разрушаться','to collapse','Ф'),
('разъединить','to separate','Д'),('разъединять','to separate','Д'),
('разъединяться','to separate','Д'),('разъяснить','to clarify','ОБ'),
('разъяснять','to clarify','ОБ'),('разъясняться','to be clarified','ОБ'),
('раскалить','to heat red-hot','Д'),('раскрывать','to reveal','Д'),
('раскрываться','to be revealed','Д'),('раскрыть','to reveal','Д'),
('расписываться','to sign','Д'),('расплавить','to melt down','Д'),
('расположить','to arrange','Д'),('распределить','to distribute','Д'),
('распространить','to spread','Д'),('распространяться','to spread','Д'),
('рассматривать','to consider','М'),('рассматриваться','to be considered','М'),
('рассмотреть','to examine','М'),('рассуждать','to reason','М'),
('рассчитать','to calculate','М'),('рассыпать','to spill','Д'),
('растворяться','to dissolve','Ф'),('расти','to grow','ФЗ'),
('расчленить','to dismember','Д'),('расчленять','to dissect','Д'),
('расширить','to widen','Д'),('расширять','to expand','Д'),
('расширяться','to expand','Д'),('регистрировать','to register','Д'),
('решать','to solve','М'),('решаться','to be solved','Д'),
('решить','to decide','М'),('руководствоваться','to be guided by','Д'),
('садиться','to sit down','ДВ'),('свергнуть','to overthrow','Д'),
('светать','to dawn','Ф'),('светиться','to glow','Ф'),
('свидетельствовать','to testify','ОБ'),('сводить','to reduce','Д'),
('сводиться','to boil down to','Д'),('связать','to connect','Д'),
('связывать','to connect','Д'),('связываться','to be connected','Д'),
('сдавать','to take an exam','Д'),('сдаваться','to surrender','Д'),
('сдать','to pass an exam','Д'),('сжечь','to burn down','Д'),
('сжиматься','to contract','Ф'),('сидеть','to sit','Д'),
('складываться','to take shape','Д'),('сколачивать','to knock together','Д'),
('скрыть','to hide','Д'),('скрыться','to hide','Д'),
('сложиться','to form','Д'),('смешать','to mix','Д'),
('смешивать','to mix','Д'),('смешиваться','to mix','Д'),
('смотреть','to look','М'),('смочить','to moisten','Д'),
('смочь','to be able','Д'),('смыкаться','to converge','Д'),
('собираться','to gather','Д'),('соблюдать','to observe','Д'),
('соблюдаться','to be observed','Д'),('соблюсти','to comply with','Д'),
('собрать','to gather','Д'),('совать','to poke','Д'),
('совершать','to commit','Д'),('совершаться','to happen','Д'),
('совершенствоваться','to improve oneself','Д'),('совершить','to accomplish','Д'),
('советовать','to advise','ОБ'),('совпадать','to coincide','Д'),
('согласиться','to agree','ОБ'),('согреваться','to warm up','Ф'),
('содержать','to contain','Д'),('содержаться','to be contained','Д'),
('соединять','to join','Д'),('соединяться','to join','Д'),
('создавать','to create','Д'),('создаваться','to be created','Д'),
('создать','to create','Д'),('созреть','to mature','ФЗ'),
('сократить','to shorten','Д'),('соответствовать','to correspond','Д'),
('сопоставить','to collate','М'),('сопоставлять','to compare','М'),
('соприкасаться','to touch','Д'),('сопровождаться','to be accompanied','Д'),
('сослаться','to refer to','ОБ'),('составиться','to be formed','Д'),
('состояться','to take place','Д'),('сохранять','to preserve','Д'),
('сплести','to weave','Д'),('спорить','to argue','ОБ'),
('способствовать','to promote','Д'),('спрашивать','to ask','ОБ'),
('спрашиваться','to be asked','ОБ'),('спускаться','to descend','ДВ'),
('сравнивать','to compare','М'),('сравнить','to compare','М'),
('ссылаться','to refer to','ОБ'),('ставить','to put','Д'),
('ставиться','to be put','Д'),('стараться','to try','Д'),
('стоить','to cost','Д'),('стоять','to stand','Д'),
('стремиться','to strive','Д'),('строить','to build','Д'),
('строиться','to be built','Д'),('струить','to stream','Ф'),
('судить','to judge','М'),('сужать','to narrow','Д'),
('сузить','to narrow','Д'),('сушить','to dry','Д'),
('сформулировать','to formulate','ОБ'),('считать','to consider','М'),
('считаться','to be considered','Д'),('сшить','to sew','Д'),
('сыграть','to play','Д'),('тереть','to rub','Д'),
('терпеть','to endure','Д'),('терять','to lose','Д'),
('течь','to flow','Ф'),('толковаться','to be interpreted','ОБ'),
('тонуть','to sink','ДВ'),('тратить','to spend','Д'),
('требовать','to demand','ОБ'),('требоваться','to be required','Д'),
('трогать','to touch','Д'),('трудиться','to labour','Д'),
('тухнуть','to go out','Ф'),('убедить','to convince','ОБ'),
('убедиться','to make sure','М'),('убеждать','to convince','ОБ'),
('убеждаться','to be convinced','М'),('убить','to kill','Д'),
('увековечить','to immortalize','Д'),('увеличиваться','to increase','Д'),
('уверять','to assure','ОБ'),('увлекаться','to be keen on','М'),
('удаваться','to succeed','Д'),('ударить','to hit','Д'),
('удаться','to succeed','Д'),('удовлетвориться','to be satisfied','М'),
('удовлетворять','to satisfy','Д'),('удостоить','to honour','Д'),
('удушать','to strangle','Д'),('узнавать','to recognize','П'),
('узнать','to find out','П'),('указываться','to be indicated','ОБ'),
('уклоняться','to evade','Д'),('укрепить','to strengthen','Д'),
('укреплять','to strengthen','Д'),('уловить','to catch','Д'),
('улыбнуться','to smile','ФЗ'),('уменьшаться','to decrease','Д'),
('умереть','to die','ФЗ'),('уметь','to know how','М'),
('умирать','to die','ФЗ'),('умозаключать','to infer','М'),
('умозаключить','to infer','М'),('уничтожать','to destroy','Д'),
('употребить','to use','Д'),('употреблять','to use','Д'),
('употребляться','to be used','Д'),('управлять','to manage','Д'),
('усвоить','to assimilate','М'),('усматривать','to discern','М'),
('усовершенствовать','to perfect','Д'),('устанавливать','to establish','Д'),
('устанавливаться','to be established','Д'),('установить','to establish','Д'),
('устареть','to become obsolete','Д'),('устранять','to eliminate','Д'),
('усыплять','to lull to sleep','Д'),('утвердить','to approve','Д'),
('утверждаться','to assert oneself','Д'),('уточнить','to specify','ОБ'),
('уточняться','to be specified','ОБ'),('участвовать','to participate','Д'),
('учесть','to take into account','М'),('учить','to teach','Д'),
('учиться','to study','М'),('уяснить','to clarify for oneself','М'),
('фиксировать','to record','Д'),('фиксироваться','to be recorded','Д'),
('формулироваться','to be formulated','ОБ'),('характеризовать','to characterize','ОБ'),
('характеризоваться','to be characterized','Д'),('хотеть','to want','М'),
('чаять','to hope','М'),('числиться','to be listed','Д'),
('читать','to read','Д'),('экспериментировать','to experiment','П'),
('электризовать','to electrify','Д'),('явиться','to appear','Д'),
]

eng = JnanaEngine(pref_lang='ru')
ok = bad = 0
for ru, en, pc in V:
    cid, msg = eng.add_concept(ru, P[pc], lang='ru', universum_id=1, terms=[(en,'en')])
    if cid is None:
        bad += 1; print('FAIL', msg)
    else:
        ok += 1
        if 'already' in str(msg): print('dup', msg)
print(f'ok={ok} fail={bad}')
eng.rebuild(); eng.define()
eng.cur.execute('SELECT COUNT(*) FROM concept')
print('concepts:', eng.cur.fetchone()[0])
eng.close()
