# -*- coding: utf-8 -*-
# Глаголы, партия 2 (281–560)
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, r'G:\Projects\conceptuum')
from jnana_engine import JnanaEngine

P = {'Д':'действие','М':'ментальный процесс','ДВ':'движение','ОБ':'общение',
     'Ф':'физический процесс','ФЗ':'физиологический процесс','П':'познание'}

V = [
('облекаться','to clothe oneself','Д'),('облечь','to clothe','Д'),
('обмениваться','to exchange','Д'),('обнажать','to bare','Д'),
('обнаруживать','to discover','П'),('обнаружить','to discover','П'),
('обобщать','to generalize','М'),('обобщить','to generalize','М'),
('обогащаться','to be enriched','Д'),('обозначать','to denote','Д'),
('обозначаться','to be denoted','Д'),('обозначить','to denote','Д'),
('оборудовать','to equip','Д'),('обосновать','to substantiate','М'),
('обосновывать','to substantiate','М'),('обосновываться','to be based','М'),
('образовать','to form','Д'),('образоваться','to form','Д'),
('обратиться','to turn to','ОБ'),('обращать','to convert','Д'),
('обращаться','to address','Д'),('обречь','to doom','Д'),
('обстоять','to be situated','Д'),('обсуждать','to discuss','ОБ'),
('обсуждаться','to be discussed','ОБ'),('обусловить','to condition','Д'),
('обусловливать','to determine','Д'),('общаться','to communicate','ОБ'),
('объединить','to unite','Д'),('объединять','to unite','Д'),
('объяснить','to explain','ОБ'),('объяснять','to explain','ОБ'),
('объясняться','to be explained','ОБ'),('обязать','to oblige','Д'),
('овладевать','to master','Д'),('оголить','to bare','Д'),
('ограничивать','to limit','Д'),('ограничиваться','to be limited','Д'),
('ограничить','to limit','Д'),('ограничиться','to confine oneself','Д'),
('одержать','to win','Д'),('ожидать','to expect','М'),
('ознакомить','to acquaint','ОБ'),('оказаться','to turn out','Д'),
('оказывать','to render','Д'),('оказываться','to turn out','Д'),
('окаменеть','to petrify','Ф'),('оклеветать','to slander','ОБ'),
('окружать','to surround','Д'),('окучивать','to hill up','Д'),
('опираться','to rely','Д'),('описывать','to describe','ОБ'),
('оправдать','to justify','ОБ'),('оправдаться','to justify oneself','ОБ'),
('оправдываться','to be justified','Д'),('определить','to define','М'),
('определяться','to be determined','Д'),('опровергать','to refute','М'),
('опровергаться','to be refuted','М'),('опровергнуть','to refute','М'),
('опрокинуть','to overturn','Д'),('опускаться','to descend','ДВ'),
('опустить','to lower','Д'),('организовать','to organize','Д'),
('организоваться','to get organized','Д'),('освещать','to illuminate','Д'),
('осложнять','to complicate','Д'),('основать','to found','Д'),
('основываться','to be based','Д'),('осознать','to realize','М'),
('оспаривать','to contest','ОБ'),('оспорить','to dispute','ОБ'),
('оставить','to leave','Д'),('оставлять','to leave','Д'),
('остановиться','to stop','ДВ'),('остаться','to remain','Д'),
('осуждать','to condemn','ОБ'),('осуществляться','to be realized','Д'),
('отбрасывать','to discard','Д'),('отбрасываться','to be thrown back','Д'),
('отвергаться','to be rejected','Д'),('отвергнуть','to reject','Д'),
('ответить','to answer','ОБ'),('отвечать','to answer','ОБ'),
('отвлекать','to distract','Д'),('отвлекаться','to be distracted','М'),
('отвлечь','to abstract','Д'),('отвлечься','to be distracted','М'),
('отвыкнуть','to get out of habit','Д'),('отграничивать','to delimit','Д'),
('отграничить','to delimit','Д'),('отдаваться','to devote oneself','Д'),
('отдалить','to move away','Д'),('отделить','to separate','Д'),
('отделяться','to separate','Д'),('отказаться','to refuse','Д'),
('отказываться','to refuse','Д'),('откинуть','to throw back','Д'),
('отклонить','to reject','Д'),('отклониться','to deviate','ДВ'),
('отклонять','to deflect','Д'),('отклоняться','to deviate','ДВ'),
('открыть','to discover','П'),('отличать','to distinguish','М'),
('отличаться','to differ','Д'),('отличить','to distinguish','М'),
('отметить','to note','ОБ'),('отнести','to attribute','Д'),
('отображать','to reflect','М'),('отображаться','to be reflected','М'),
('отобразить','to reflect','М'),('отобразиться','to be reflected','М'),
('отобрать','to take away','Д'),('отозваться','to respond','ОБ'),
('отражать','to reflect','М'),('отражаться','to be reflected','М'),
('отразиться','to be reflected','М'),('отрицаться','to be denied','М'),
('отстать','to lag behind','Д'),('оттенить','to set off','Д'),
('отходить','to depart','ДВ'),('отыскать','to find','Д'),
('отыскивать','to seek','Д'),('оформиться','to take shape','Д'),
('охватить','to encompass','Д'),('охватывать','to cover','Д'),
('охватываться','to be covered','Д'),('охладить','to cool','Д'),
('падать','to fall','ДВ'),('перебирать','to sort through','Д'),
('перевыполнить','to overfulfil','Д'),('перевыполнять','to overfulfil','Д'),
('переглянуться','to exchange glances','ОБ'),('передаваться','to be transmitted','Д'),
('передать','to pass on','Д'),('перейти','to cross over','ДВ'),
('перекрещиваться','to intersect','Д'),('перенести','to transfer','Д'),
('переноситься','to be transferred','Д'),('переплести','to bind','Д'),
('перерабатывать','to process','Д'),('пересекаться','to intersect','Д'),
('пересечься','to intersect','Д'),('переставать','to stop','Д'),
('перестать','to stop','Д'),('переходить','to pass over','ДВ'),
('печататься','to be printed','Д'),('писать','to write','Д'),
('питать','to nourish','Д'),('питаться','to feed','ФЗ'),
('платить','to pay','Д'),('пленить','to captivate','Д'),
('плестись','to trudge','ДВ'),('плыть','to swim','ДВ'),
('победить','to win','Д'),('повиснуть','to hang down','Д'),
('повторяться','to repeat','Д'),('повышать','to raise','Д'),
('погибнуть','to perish','ФЗ'),('погрузить','to immerse','Д'),
('подавать','to serve','Д'),('подавлять','to suppress','Д'),
('подвергаться','to undergo','Д'),('подвергнуть','to subject','Д'),
('подвергнуться','to undergo','Д'),('подвести','to bring to','Д'),
('подводить','to lead up to','Д'),('подготавливать','to prepare','Д'),
('подготовить','to prepare','Д'),('подготовиться','to prepare oneself','Д'),
('поддерживать','to support','Д'),('подлежать','to be subject to','Д'),
('подменять','to substitute','Д'),('подменяться','to be substituted','Д'),
('поднимать','to lift','Д'),('подниматься','to rise','ДВ'),
('поднять','to raise','Д'),('подобрать','to pick up','Д'),
('подписать','to sign','Д'),('подразумеваться','to be implied','М'),
('подтвердить','to confirm','ОБ'),('подтверждаться','to be confirmed','Д'),
('подходить','to approach','ДВ'),('подчеркнуть','to emphasize','ОБ'),
('подчинить','to subordinate','Д'),('подчинять','to subordinate','Д'),
('подчиняться','to obey','Д'),('подчёркивать','to underline','Д'),
('подытожить','to sum up','ОБ'),('поедать','to eat up','ФЗ'),
('пожелать','to wish','М'),('позабавить','to amuse','Д'),
('позволить','to allow','Д'),('позволять','to allow','Д'),
('познавать','to cognize','П'),('познаваться','to be cognized','П'),
('познакомиться','to get acquainted','ОБ'),('познать','to know','П'),
('поймать','to catch','Д'),('пойти','to go','ДВ'),
('показать','to show','ОБ'),('показывать','to show','ОБ'),
('показываться','to appear','Д'),('покраснеть','to blush','ФЗ'),
('поливать','to water','Д'),('положить','to put','Д'),
('получиться','to turn out','Д'),('пользоваться','to use','Д'),
('помнить','to remember','М'),('помогать','to help','Д'),
('помочь','to help','Д'),('понижаться','to decrease','Ф'),
('понизиться','to go down','Ф'),('понимать','to understand','М'),
('пониматься','to be understood','М'),('понять','to understand','М'),
('попасться','to get caught','Д'),('поручить','to entrust','Д'),
('посеять','to sow','Д'),('послужить','to serve','Д'),
('посредствовать','to mediate','Д'),('поссориться','to quarrel','ОБ'),
('поставить','to put','Д'),('построить','to build','Д'),
('поступать','to act','Д'),('поступить','to act','Д'),
('посылать','to send','Д'),('потерпеть','to suffer','Д'),
('потерять','to lose','Д'),('потратить','to spend','Д'),
('потреблять','to consume','Д'),('потребоваться','to be required','Д'),
('появиться','to appear','Д'),('появляться','to appear','Д'),
('пояснить','to clarify','ОБ'),('поясняться','to be clarified','ОБ'),
('превратить','to turn into','Д'),('превратиться','to turn into','Д'),
('превращать','to transform','Д'),('превращаться','to be transformed','Д'),
('предвещать','to portend','Д'),('предложить','to propose','ОБ'),
('предостерегать','to caution','ОБ'),('предохранить','to protect','Д'),
('предполагать','to suppose','М'),('предполагаться','to be supposed','М'),
('предположить','to assume','М'),('предсказать','to predict','ОБ'),
('представить','to present','ОБ'),('представиться','to seem','М'),
('представляться','to seem','М'),('предстать','to appear','Д'),
('предшествовать','to precede','Д'),('предъявляться','to be presented','Д'),
('прекратить','to cease','Д'),('преобразовать','to transform','Д'),
('преобразоваться','to be transformed','Д'),('преобразовывать','to transform','Д'),
('пресекать','to suppress','Д'),('преувеличивать','to exaggerate','ОБ'),
('прибавить','to add','Д'),('прибегать','to resort','Д'),
('приближать','to bring nearer','Д'),('привлекать','to attract','Д'),
('приводиться','to be cited','Д'),('придавать','to impart','Д'),
('придать','to give','Д'),('признаваться','to be recognized','Д'),
('признать','to recognize','М'),('прийти','to come','ДВ'),
('прийтись','to fall on','Д'),('приложить','to attach','Д'),
('применить','to apply','Д'),('применять','to apply','Д'),
('применяться','to be applied','Д'),('принадлежать','to belong','Д'),
('принести','to bring','Д'),('принимать','to accept','Д'),
('приниматься','to be accepted','Д'),('принять','to accept','Д'),
('приобрести','to acquire','Д'),('приобретаться','to be acquired','Д'),
('приписываться','to be attributed','Д'),('прислать','to send','Д'),
('приспособить','to adapt','Д'),('приспособлять','to adapt','Д'),
('приспособляться','to adapt oneself','Д'),('присутствовать','to be present','Д'),
('притягивать','to attract','Д'),('притягиваться','to be attracted','Д'),
('приходить','to arrive','ДВ'),('приходиться','to have to','Д'),
]

eng = JnanaEngine(pref_lang='ru')
ok = bad = 0
for ru, en, pc in V:
    cid, msg = eng.add_concept(ru, P[pc], lang='ru', universum_id=1, terms=[(en,'en')])
    if cid is None:
        bad += 1; print('FAIL', msg)
    else:
        ok += 1
        if 'already' in str(msg): print('dup', msg)
print(f'ok={ok} fail={bad}')
eng.rebuild(); eng.define()
eng.cur.execute('SELECT COUNT(*) FROM concept')
print('concepts:', eng.cur.fetchone()[0])
eng.close()
