# -*- coding: utf-8 -*-
# Глаголы, партия 1 (1–280). Коды родов: Д=действие М=ментальный процесс
# ДВ=движение ОБ=общение Ф=физический процесс ФЗ=физиологический процесс П=познание
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, r'G:\Projects\conceptuum')
from jnana_engine import JnanaEngine

P = {'Д':'действие','М':'ментальный процесс','ДВ':'движение','ОБ':'общение',
     'Ф':'физический процесс','ФЗ':'физиологический процесс','П':'познание'}

V = [
('абстрагировать','to abstract','М'),('абстрагироваться','to be abstracted','М'),
('анализировать','to analyze','М'),('беречь','to take care of','Д'),
('блестеть','to shine','Ф'),('бойкотировать','to boycott','Д'),
('бояться','to fear','М'),('браться','to undertake','Д'),
('бросаться','to rush','ДВ'),('валить','to fell','Д'),
('ввести','to introduce','Д'),('вводить','to introduce','Д'),
('верить','to believe','М'),('весить','to weigh','Д'),
('вести','to lead','Д'),('взорваться','to explode','Ф'),
('взяться','to set about','Д'),('висеть','to hang','Д'),
('виться','to twine','ДВ'),('вкладывать','to put in','Д'),
('включать','to include','Д'),('включаться','to be included','Д'),
('включить','to include','Д'),('владеть','to own','Д'),
('влечь','to entail','Д'),('влиять','to influence','Д'),
('внести','to bring in','Д'),('возбуждать','to excite','ФЗ'),
('возбуждаться','to get excited','ФЗ'),('воздействовать','to act upon','Д'),
('возить','to cart','Д'),('возразить','to object','ОБ'),
('возрастать','to grow','Ф'),('возродить','to revive','Д'),
('войти','to enter','ДВ'),('воспитывать','to bring up','Д'),
('восполнить','to replenish','Д'),('воспользоваться','to make use of','Д'),
('воспринимать','to perceive','М'),('восприниматься','to be perceived','М'),
('воспроизводить','to reproduce','Д'),('восстанавливать','to restore','Д'),
('восстанавливаться','to be restored','Д'),('восстановить','to restore','Д'),
('впадать','to fall into','ДВ'),('вписать','to inscribe','Д'),
('вращать','to rotate','Д'),('вращаться','to rotate','ДВ'),
('вскрывать','to reveal','Д'),('вскрыть','to reveal','Д'),
('вспыхивать','to flare up','Ф'),('встать','to stand up','ДВ'),
('встретить','to meet','Д'),('встречать','to meet','Д'),
('встречаться','to occur','Д'),('вступать','to enter','Д'),
('вступить','to enter','Д'),('выбрасывать','to throw out','Д'),
('выбрать','to choose','М'),('вывести','to derive','Д'),
('выводиться','to be derived','Д'),('выдвинуть','to put forward','Д'),
('выделить','to single out','Д'),('выделиться','to stand out','Д'),
('выделяться','to be distinguished','Д'),('выдержать','to withstand','Д'),
('выдолбить','to hollow out','Д'),('выдумать','to invent','М'),
('выжечь','to burn out','Д'),('вызвать','to cause','Д'),
('вызывать','to cause','Д'),('вызываться','to volunteer','Д'),
('выиграть','to win','Д'),('выйти','to go out','ДВ'),
('вылететь','to fly out','ДВ'),('вынудить','to force','Д'),
('выполнить','to fulfil','Д'),('выполнять','to perform','Д'),
('выполняться','to be performed','Д'),('вырабатываться','to be developed','Д'),
('выработаться','to become formed','Д'),('выразить','to express','ОБ'),
('вырваться','to break out','ДВ'),('высказать','to state','ОБ'),
('высказаться','to speak out','ОБ'),('высказывать','to express','ОБ'),
('высказываться','to express oneself','ОБ'),('выставить','to exhibit','Д'),
('выставляться','to be exhibited','Д'),('выступать','to speak publicly','ОБ'),
('выступить','to come forward','ОБ'),('вытеснить','to displace','Д'),
('выхватить','to snatch','Д'),('вычислить','to compute','М'),
('выявить','to reveal','Д'),('выявлять','to reveal','Д'),
('выяснять','to find out','П'),('выясняться','to become clear','Д'),
('гарантировать','to guarantee','Д'),('гибнуть','to perish','ФЗ'),
('гласить','to state','ОБ'),('говориться','to be said','ОБ'),
('гореть','to burn','Ф'),('готовиться','to prepare','Д'),
('даваться','to be given','Д'),('двигать','to move','ДВ'),
('двигаться','to move','ДВ'),('действовать','to act','Д'),
('делаться','to become','Д'),('делить','to divide','Д'),
('делиться','to be divided','Д'),('добиваться','to strive for','Д'),
('добываться','to be obtained','Д'),('добыть','to obtain','Д'),
('доказать','to prove','Д'),('доказываться','to be proven','Д'),
('дополнить','to supplement','Д'),('дополняться','to be supplemented','Д'),
('допускать','to admit','Д'),('допускаться','to be admitted','Д'),
('допустить','to allow','Д'),('доставлять','to deliver','Д'),
('достать','to get','Д'),('достигать','to reach','Д'),
('достигаться','to be achieved','Д'),('достигнуть','to achieve','Д'),
('думать','to think','М'),('дуть','to blow','Ф'),
('дышать','to breathe','ФЗ'),('есть','to eat','ФЗ'),
('жать','to press','Д'),('ждать','to wait','Д'),
('желать','to wish','М'),('жить','to live','ФЗ'),
('забывать','to forget','М'),('зависеть','to depend','Д'),
('завоевать','to conquer','Д'),('завянуть','to wither','ФЗ'),
('загораться','to catch fire','Ф'),('задать','to set','Д'),
('заимствовать','to borrow','Д'),('заинтересовать','to interest','Д'),
('зайти','to drop in','ДВ'),('закипать','to boil','Ф'),
('заключить','to conclude','Д'),('закрепить','to fix','Д'),
('закрепиться','to become fixed','Д'),('закреплять','to fasten','Д'),
('закрепляться','to be fastened','Д'),('заложить','to lay','Д'),
('замедлять','to slow down','Д'),('заменить','to replace','Д'),
('заменять','to replace','Д'),('замерзать','to freeze','Ф'),
('заметить','to notice','М'),('замечать','to notice','М'),
('замёрзнуть','to freeze','Ф'),('занимать','to occupy','Д'),
('заниматься','to engage in','Д'),('запечатлеть','to imprint','Д'),
('запечатлеться','to be imprinted','Д'),('записать','to write down','Д'),
('заплатить','to pay','Д'),('запомнить','to memorize','М'),
('запретить','to forbid','Д'),('запрещать','to prohibit','Д'),
('запутать','to confuse','Д'),('заслуживать','to deserve','Д'),
('заслужить','to deserve','Д'),('заставить','to make do','Д'),
('затруднять','to complicate','Д'),('защищать','to defend','Д'),
('знавать','to know','М'),('зреть','to see','М'),
('играть','to play','Д'),('избежать','to avoid','Д'),
('изведывать','to experience','Д'),('излагать','to expound','ОБ'),
('изложить','to set forth','ОБ'),('изменить','to change','Д'),
('измениться','to change','Д'),('изменять','to change','Д'),
('изменяться','to change','Д'),('измерить','to measure','Д'),
('измеряться','to be measured','Д'),('изображать','to depict','Д'),
('изображаться','to be depicted','Д'),('изобразить','to depict','Д'),
('изолировать','to isolate','Д'),('изучать','to study','П'),
('изучить','to learn thoroughly','П'),('именовать','to name','ОБ'),
('интересовать','to interest','Д'),('интересоваться','to be interested in','М'),
('исказить','to distort','Д'),('исключать','to exclude','Д'),
('исключаться','to be excluded','Д'),('исполниться','to come true','Д'),
('использовать','to use','Д'),('исследовать','to research','П'),
('истолковывать','to interpret','М'),('исходить','to proceed from','Д'),
('исчезать','to disappear','Ф'),('исчерпывать','to exhaust','Д'),
('казаться','to seem','М'),('калить','to heat','Д'),
('касаться','to concern','Д'),('кататься','to ride','ДВ'),
('кипеть','to boil','Ф'),('классифицировать','to classify','М'),
('ковать','to forge','Д'),('колебаться','to oscillate','Ф'),
('констатировать','to state as fact','ОБ'),('кончаться','to end','Д'),
('корить','to reproach','ОБ'),('критиковать','to criticize','ОБ'),
('крыться','to lie hidden','Д'),('лежать','to lie','Д'),
('летать','to fly','ДВ'),('лететь','to fly','ДВ'),
('лить','to pour','Д'),('лишить','to deprive','Д'),
('любить','to love','М'),('менять','to change','Д'),
('меняться','to change','Д'),('мешать','to hinder','Д'),
('морозить','to freeze','Д'),('мочить','to wet','Д'),
('мылиться','to lather','Д'),('мыслить','to think','М'),
('мыслиться','to be conceived','М'),('наблюдать','to observe','М'),
('наблюдаться','to be observed','М'),('набухать','to swell','Ф'),
('навлечь','to bring upon','Д'),('наградить','to award','Д'),
('нагреваться','to heat up','Ф'),('нагреть','to heat','Д'),
('нагреться','to warm up','Ф'),('надевать','to put on','Д'),
('надеть','to put on','Д'),('назвать','to name','ОБ'),
('найти','to find','Д'),('накаливаться','to glow','Ф'),
('накопить','to accumulate','Д'),('наладить','to adjust','Д'),
('намагничивать','to magnetize','Д'),('наносить','to apply','Д'),
('напасть','to attack','Д'),('напереть','to lean on','Д'),
('написать','to write','Д'),('напоминать','to remind','ОБ'),
('направить','to direct','Д'),('направляться','to head','ДВ'),
('нарисовать','to draw','Д'),('нарушать','to violate','Д'),
('нарушаться','to be violated','Д'),('нарушить','to violate','Д'),
('населять','to inhabit','Д'),('наслать','to send down','Д'),
('настаивать','to insist','ОБ'),('наступать','to advance','ДВ'),
('научиться','to learn','М'),('находить','to find','Д'),
('начать','to begin','Д'),('начаться','to begin','Д'),
('начинать','to begin','Д'),('начинаться','to begin','Д'),
('недоставать','to be lacking','Д'),('нести','to carry','Д'),
('носить','to carry','Д'),('нуждаться','to need','Д'),
('обдумывать','to ponder','М'),('обеспечивать','to ensure','Д'),
('обладать','to possess','Д'),('облегчать','to facilitate','Д'),
('облегчить','to facilitate','Д'),
]

eng = JnanaEngine(pref_lang='ru')
ok = bad = 0
for ru, en, pc in V:
    cid, msg = eng.add_concept(ru, P[pc], lang='ru', universum_id=1, terms=[(en,'en')])
    if cid is None:
        bad += 1; print('FAIL', msg)
    else:
        ok += 1
        if 'already' in str(msg): print('dup', msg)
print(f'ok={ok} fail={bad}')
eng.rebuild(); eng.define()
eng.cur.execute('SELECT COUNT(*) FROM concept')
print('concepts:', eng.cur.fetchone()[0])
eng.close()
